### ISSUE TITLE
使用oss 异步上传的时候,成功了.在 onSuccess 中返回的 json 数据大于1.3k 时,为 null

### ISSUE THREAD

**Issue by wuyalun198612** [aliyun/aliyun-oss-android-sdk#106]
使用Android oss 异步上传即 ossClient.asyncPutObject()成功了.在 onSuccess 回调中返回的 json 数据大于1.3k,则返回的 serverCallbackreturnBody 为 null.
当小于1.3k 左右时,能正常返回.查看 sdk 文档,有说默认是1m. 这完全不符合描述.
在 ios 端该功能正常,当json 数据大于1.3k 也能正常返回.
这应该是一个 bug. 麻烦解决下.谢谢

**Comment by 1019272778** [comment]
能提供一下你的callback 地址吗？另可以抓包看看callback 返回的实际内容吗？是不是一些特殊字符原因？

**Comment by wuyalun198612** [comment]
https://smapi-dev.sumian.com/oss/callback/bigger

返回 json 数据小于 1.3 K 的地址：
https://smapi-dev.sumian.com/oss/callback/smaller  

两个地址都是用 POST 方法

ios 端使用正常.  这边我在之后在 aliyun 提交了工单.你们有同事回复我说复现了该 bug 了.你们可以同步一下信息.谢谢

**Comment by 1019272778** [comment]
谢谢反馈。问题已经定位。您可以在请求前添加如下设置，确认是否能解决。

ObjectMetadata metadata = new ObjectMetadata();
metadata.addUserMetadata("X-Oss-meta-Key2", "Value2");
put.setMetadata(metadata);

**Comment by wuyalun198612** [comment]
经验证 ,添加该 http  header  可以解决问题.不需要更新sdk 版本
