### ISSUE TITLE
ResumableUploadRequest 删除失败

### ISSUE THREAD

**Issue by zzg19901210** [aliyun/aliyun-oss-android-sdk#109]
1.ResumableUploadRequest 请求进行上传文件，如果本地手机带宽的上传速度不稳定或者上传速度小于100Kb会出现java.net.SocketException: Broken pipe ,这个会上传终止，无法会返回上传回调发放。
2.  ResumableUploadRequest如何调用暂停上传和继续上传方法。

**Comment by 1019272778** [comment]
@zzg19901210 你好，ResumableUploadRequest 会把一个大文件分片上传。只有所有分片任务都处理完以后，如果有分片不成功，会有上传失败的回调。 ResumableUploadRequest如何调用暂停上传和继续上传方法。请参见：https://help.aliyun.com/document_detail/32047.html中断点上传部分。

**Comment by qiongtony** [comment]
> @zzg19901210 你好，ResumableUploadRequest 会把一个大文件分片上传。只有所有分片任务都处理完以后，如果有分片不成功，会有上传失败的回调。 ResumableUploadRequest如何调用暂停上传和继续上传方法。请参见：[https://help.aliyun.com/document_detail/32047.html中断点上传部分。](https://help.aliyun.com/document_detail/32047.html%E4%B8%AD%E6%96%AD%E7%82%B9%E4%B8%8A%E4%BC%A0%E9%83%A8%E5%88%86%E3%80%82)

链接已失效，请问还有新的链接吗？
