### ISSUE TITLE
分片上传，无法改变文件的读写权限

### ISSUE THREAD

**Issue by xienb** [aliyun/aliyun-oss-android-sdk#111]
bucket为私有，使用分片上传，调用initiatemultipartupload初始化object的时候，设置请求头如下：
ObjectMetadata metadata=new ObjectMetadata();
metadata.setHeader("x-oss-object-acl", "public-read");
但是上传完成以后，文件依然是私有

**Comment by 1019272778** [comment]
@xienb 请在CompleteMultipartUpload 操作添加属性
