### ISSUE TITLE
gradle 添加依赖，打包报错，Error:Execution failed for task ':transformClassesAndResourcesWithProguardForRelease'.

### ISSUE THREAD

**Issue by hedongBlog** [aliyun/aliyun-oss-android-sdk#114]

**Comment by 1019272778** [comment]
@hedongBlog 
你好，这个问题可以参见网上的一些说明
https://blog.csdn.net/louyxlovess/article/details/51014766

另，oss的混淆配置也可以参考如下信息
https://help.aliyun.com/document_detail/32043.html
