### ISSUE TITLE
400，request parse msg error

### ISSUE THREAD

**Issue by chenbojun** [aliyun/aliyun-oss-android-sdk#115]
通过putObject上传图片，偶现400，request parse msg error的错误。我这边不是通过你们sdk调用的，是自己用的OkHttp上传图片。

提示如下：
{"X-Swift-Error":["request parse msg error"],"OkHttp-Selected-Protocol":["http/1.1"],"Via":["cache5.cn539[0,400-1,M], cache3.cn539[2,0]"],"Content-Type":["text/html"],"Timing-Allow-Origin":["*"],"OkHttp-Received-Millis":["1526461805826"],"Server":["Tengine"],"OkHttp-Response-Source":["NETWORK 400"],"Content-Length":["0"],"EagleId":["9dff901715264618073545597e"],"Connection":["keep-alive"],"OkHttp-Sent-Millis":["1526461804737"]}

**Comment by chenbojun** [comment]
出现的概率比较低，但是确实偶现这个错误

**Comment by 1019272778** [comment]
从错误返回的内容看，这个请求还没有到达oss 服务器。如果走的是运营商公网，不排除一些网络问题。

**Comment by RyanDeng** [comment]
`"Server":["Tengine"]` 这个是不是已经到了阿里云的网关服务了？我们这里也遇到这个问题

**Comment by smelloftime** [comment]
您好，目前我们iOS端使用Alamofire上传附件到阿里云OSS也是同样的报错信息
但是是低频率的触发，比较难复现
有解决方案么？
