### ISSUE TITLE
CertPathValidatorException

### ISSUE THREAD

**Issue by weifangtao** [aliyun/aliyun-oss-android-sdk#116]
在红米5note上图片上传的时候会出现这种bug，是怎么回事：com.alibaba.sdk.android.oss.ClientException: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
                                                                                 [ErrorMessage]: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

**Comment by 1019272778** [comment]
看异常主要是SSL握手时产生的问题。sdk用的网络层是支持https协议的。
目前因为安全漏洞oss server 仅支持TLS协议。如果部分手机网络模块是用SSL库，不排除可能会出现https握手问题。
参见如下文章。
https://www.wolfcstech.com/2017/06/08/android_tls_version_issue/

这个错误是android 系统层抛出的错误。可以先尝试根据手机型号改成http协议。
