### ISSUE TITLE
为什么没有MNS的单独jar包，官网jar包太老了，使用oss，都不能获取下载进度

### ISSUE THREAD

**Issue by Likeyong** [aliyun/aliyun-oss-android-sdk#117]
这还怎么用呀

**Comment by 1019272778** [comment]
oss 是可以设置下载进度的。
https://help.aliyun.com/document_detail/32048.html
有介绍如何设置下载进度

**Comment by Likeyong** [comment]
我现在的需求是  要使用MNS还要使用OSS，  用最新的OSS，MNS就没有了，
