### ISSUE TITLE
GetObjectRequest 的setProgressListener 出错。。。很无奈

### ISSUE THREAD

**Issue by Likeyong** [aliyun/aliyun-oss-android-sdk#118]
Error:(1263, 6) 错误: 找不到符号
符号:   方法 setProgressListener(<匿名OSSProgressCallback<GetObjectRequest>>)
位置: 类型为GetObjectRequest的变量 get

**Comment by 1019272778** [comment]
请问你使用的oss 版本是那个？建议使用oss 最新版本的sdk

**Comment by Likeyong** [comment]
用的是2.3.0，最最新的版本  阿里云MNS  就不能使用了啊

**Comment by 1019272778** [comment]
setProgressListener 是后续版本添加的功能。我也不清楚为何mns 没有支持最新oss sdk
