### ISSUE TITLE
关于编译打jar包的语句问题

### ISSUE THREAD

**Issue by yaochangliang159** [aliyun/aliyun-oss-android-sdk#123]
你的ReadMe中如下写道：

Run the packaging script. JDK 1.7 is required
$ ./gradlew releaseJar
而上一步你已经
cd aliyun-oss-android-sdk/oss-android-sdk/
进入到oss-android-sdk里面了，
./ 代表的意思是当前目录下，可是oss-android-sdk的文件夹下就没有gradlew.bat的文件。自然而然也就执行不了这条语句了，提示的截图如下：
![tim 20180625175841](https://user-images.githubusercontent.com/13497352/41844159-e363ed30-78a1-11e8-9946-736475c4412c.png)
倒是aliyun-oss-android-sdk有个gradlew.bat文件，我执行了，也是不合适,截图如下：
![tim 20180625180210](https://user-images.githubusercontent.com/13497352/41844229-2596bb6a-78a2-11e8-979d-117e7ef454c5.png)

**Comment by 1019272778** [comment]
您可以先了解一些gradle的语法
