### ISSUE TITLE
为什么拼接url的时候没有把port拼接上去呢？

### ISSUE THREAD

**Issue by zcbiner** [aliyun/aliyun-oss-android-sdk#124]
我传入的endpoint是：http://ip:port  这种形式。 被oss封装成了一个URI，然后我发现在访问oss组装url时，url不包含端口信息。
RequestMessage类中buildCanonicalURL的方法只会拿URI的host拼接成一个url：

String scheme = endpoint.getScheme();
String originHost = endpoint.getHost();
if (OSSUtils.isIP(originHost)) {
   baseURL = scheme + "://" + originHost + "/" + bucketName;

**Comment by 1019272778** [comment]
才用的是http协议，走的是默认端口
