### ISSUE TITLE
okHttp版本

### ISSUE THREAD

**Issue by zzyandroid0425** [aliyun/aliyun-oss-android-sdk#13]
麻烦能不能尽快升级至okhttp:3.0.1呢，我们项目也是依赖于okHttp，并准备升级至最新版。谢谢。

**Comment by xuyecan** [comment]
好的，明天收假回去我就处理。

**Comment by zzyandroid0425** [comment]
谢谢

**Comment by xuyecan** [comment]
更新后升级到小版本号 2.1.0.1，直接通过maven依赖即可。官网版本要按正常日程走。
