### ISSUE TITLE
android 9.0 异步上传图片没有回调

### ISSUE THREAD

**Issue by wholwh** [aliyun/aliyun-oss-android-sdk#135]
android 9.0 异步上传图片没有回调,模拟器和真机都一样.8.0上没问题
![image](https://user-images.githubusercontent.com/7368853/43766815-0bfa6b1c-9a66-11e8-8238-c41cd9f77d32.png)

**Comment by wholwh** [comment]
下载源码后修改targetSdk后依赖编译后没问题,不知问题的没回调的原因是什么

**Comment by lichangjian** [comment]
Android 9.0 必须走 https ，不知道是不是这个原因
