### ISSUE TITLE
why android sdk can not put object through signedUrl like .net sdk

### ISSUE THREAD

**Issue by fanfanxiaozu** [aliyun/aliyun-oss-android-sdk#14]
this is .net sdk's way 
var result = client.PutObject(signedUrl, fileToUpload);

**Comment by xuyecan** [comment]
Once you acheive an url which is signed at the phone-end, you can simply upload your file by some common network library such as httpurlconnection/okhttp. The Android SDK
aim at simplifying the authentication by the Aliyun STS(security token distribution) Service.

See https://help.aliyun.com/document_detail/ram/sts-api-reference/intro.html?spm=5176.product8315075_ram.4.36.suntIF .

**Comment by fanfanxiaozu** [comment]
I know what you mean,but does this multi part upload support, if  i just change the sdk's upload url with signed url
