### ISSUE TITLE
gradle 编译报错（android studio 3.0.1）

### ISSUE THREAD

**Issue by axlyb** [aliyun/aliyun-oss-android-sdk#141]
根据提示，在build.gradle中加入：
compile 'com.aliyun.dpa:oss-android-sdk:+'

编译选项：
 compileSdkVersion 26
  minSdkVersion 17
  targetSdkVersion 26

但是编译报错：
Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.aliyun.dpa:oss-android-sdk:+.

Could not resolve com.aliyun.dpa:oss-android-sdk:+.
Required by:
    project :app
 > Could not resolve com.aliyun.dpa:oss-android-sdk:+.
    > Failed to list versions for com.aliyun.dpa:oss-android-sdk.
          > Unable to load Maven meta-data from https://dl.google.com/dl/android/maven2/com/aliyun/dpa/oss-android-sdk/maven-metadata.xml.
                   > Could not get resource 'https://dl.google.com/dl/android/maven2/com/aliyun/dpa/oss-android-sdk/maven-metadata.xml'.
                               > Could not GET 'https://dl.google.com/dl/android/maven2/com/aliyun/dpa/oss-android-sdk/maven-metadata.xml'.
                                              > dl.google.com:443 failed to respond

**Comment by chinamingsss** [comment]
是否解决

**Comment by ceeyang** [comment]
Run flutter Android application with gradle in offline mode:
https://stackoverflow.com/questions/56540327/how-do-i-run-flutter-application-with-gradle-in-offline-mode
