### ISSUE TITLE
Could not read input channel file descriptors from parcel.

### ISSUE THREAD

**Issue by ChenTianSaber** [aliyun/aliyun-oss-android-sdk#143]
我们的项目需要连续不停的上传图片
然后每次上传我都会new一个Client
然后就会出现Could not read input channel file descriptors from parcel.这个错误

这个问题我查了很久，终于发现是OSS的问题，我把OSS上传的代码删了就没事了，一加上就有问题
上网查了原因，可能是OSSClient里的网络请求没有正确的关闭，或者File没有正确的关闭导致的

请测试一下这个问题

**Comment by ChenTianSaber** [comment]
我连续上传400多张图片，大概传到100多张的时候，就会出现这个问题

**Comment by duan007a** [comment]
向单个Endpoint下面的bucket中上传数据，程序应该只需要持有一个Client就可以了，每次上传图片直接调用程序所持有Client的上传API就可以的
