### ISSUE TITLE
部分网络上传报recvfrom failed: ECONNRESET错误

### ISSUE THREAD

**Issue by weizai** [aliyun/aliyun-oss-android-sdk#144]
在某些网络环境下上传文件报 recvfrom failed: ECONNRESET错误, 上传的文件大小为76KB
调用oss.asyncPutObject后会进入到onFailure回调

**Comment by 1019272778** [comment]
sdk是oss api的实现。对于具体的网络连接错误。还要看看具体的使用场景。

**Comment by weizai** [comment]
该错误如何排查,  需要提供什么样的具体使用环境？

**Comment by 1019272778** [comment]
@weizai oss android sdk是 oss 上传协议的实现。该问题看起来是网络传输链路相关。也可以参见一些网络的解决方案：
http://www.voidcn.com/article/p-vbaskgpq-gt.html
https://blog.csdn.net/w200221626/article/details/72723546

**Comment by weizai** [comment]
同样的环境下，软件+硬件+网络，七牛可以上传，阿里sdk无法上传,  猜想可能是ali的endpoint被屏蔽了, 如果想确认，怎样排查?

**Comment by 1019272778** [comment]
可以参考如下文章：
https://help.aliyun.com/knowledge_detail/59935.html
