### ISSUE TITLE
sdk 未支持 Android 9.0  https

### ISSUE THREAD

**Issue by uni7corn** [aliyun/aliyun-oss-android-sdk#145]
问题描述 ： oss  sdk 未  支持 Android 9.0  
在 Android  9.0 默认请求要求使用 https, 但是 oss sdk  当中使用的 okHttp 默认是 http 请求,所以会造成请求无法被执行..麻烦升级 sdk, 并支持 https 请求.

相关错误信息
<img width="1149" alt="wx20181029-112759 2x" src="https://user-images.githubusercontent.com/8399829/47627907-baff1e80-db6d-11e8-9503-177e6f609971.png">

<img width="1163" alt="wx20181029-112646 2x" src="https://user-images.githubusercontent.com/8399829/47627873-8db27080-db6d-11e8-8b37-c183f1ebbfab.png">

ps:[已提交工单]

相关文档:
https://developer.android.google.cn/about/versions/pie/android-9.0-changes-28
https://developer.android.google.cn/training/articles/security-config

相关关键字: 
android:usesCleartextTraffic="" #

相关 issue
#135  ?

**Comment by duan007a** [comment]
解决办法：1.在初始化OSSClient时，业务方传入参数endpoint为https的就不会出现这个问题了。
                   2.确实需要明文传输的，可以参考安卓官方博客   https://android-developers.googleblog.com/2018/04/protecting-users-with-tls-by-default-in.html开启明文传输的策略

**Comment by Zhangsongsong** [comment]
https + 2.9.0的版本就可以了！
