### ISSUE TITLE
网络没问题，一编译就会报错Unable to resolve dependency

### ISSUE THREAD

**Issue by aiyakuaile** [aliyun/aliyun-oss-android-sdk#151]
Unable to resolve dependency for ':app@debug/compileClasspath': Could not download oss-android-sdk.aar (com.aliyun.dpa:oss-android-sdk:2.9.2)
Open File
Show Details

Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not download oss-android-sdk.aar (com.aliyun.dpa:oss-android-sdk:2.9.2)
Open File
Show Details

Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not download oss-android-sdk.aar (com.aliyun.dpa:oss-android-sdk:2.9.2)
Open File
Show Details

Unable to resolve dependency for ':app@release/compileClasspath': Could not download oss-android-sdk.aar (com.aliyun.dpa:oss-android-sdk:2.9.2)
Open File
Show Details

Unable to resolve dependency for ':app@releaseUnitTest/compileClasspath': Could not download oss-android-sdk.aar (com.aliyun.dpa:oss-android-sdk:2.9.2)
Open File
Show Details

**Comment by 1019272778** [comment]
u could try get it throug some proxy.
https://www.cresco.co.jp/blog/entry/2014/
