### ISSUE TITLE
CHANGE_WIFI_STATE 是否可以去掉

### ISSUE THREAD

**Issue by kassadin** [aliyun/aliyun-oss-android-sdk#152]
看了下记录是最早的版本添加的，但没有 WifiManager 相关内代码，应该是可以去掉的吧。https://github.com/aliyun/aliyun-oss-android-sdk/blob/e7cca6619901022597ea6d28adc6f8e365c53727/oss-android-sdk/src/main/AndroidManifest.xml#L9

**Comment by 1019272778** [comment]
会在下一个大版本升级时做全面检查，如果没问题就去掉。
