### ISSUE TITLE
Glide无法在低版本Android手机加载图片

### ISSUE THREAD

**Issue by ahjsdgjnamla** [aliyun/aliyun-oss-android-sdk#159]
最近遇到了华为手机上，甚至一些低版本Android手机上加载图片失败，高版本和其他手机没问题，有没有了解Gilde大神，这是缓存出问题了，还是其他问题，用的Glide版本是4.8

**Comment by 1019272778** [comment]
这个我也没有用过，可以在网上搜寻一些文章或者debug源码看看原因
可以给一些资料：https://www.jianshu.com/p/757bb9ad10c6
