### ISSUE TITLE
new OSSClient导致线程数增多

### ISSUE THREAD

**Issue by start141** [aliyun/aliyun-oss-android-sdk#17]
有些情况下是根据Request不同来设置不同的鉴权方式的，现在sdk的做法是按OSSClient来设置鉴权，导致需要采用不同的鉴权方式的时候需要new新的OSSClient，这样会导致又生成了新的一个线程池，new的OSSClient越多的时候，应用产生的线程数量不就越多了吗。

这个问题能不能参照一下AsyncTask，在sdk内部把线程池设置成static的，甚至还可以在OSSClient的构造函数里面传入自己的线程池（sdk也可以提供一个默认static的线程池供开发者引用）

**Comment by xuyecan** [comment]
你说得对，我这里疏忽了这种场景。下个版本我会把这一点考虑进去，相关patch提交后，我在这里回复通知下你。

**Comment by start141** [comment]
好的，谢谢！

**Comment by xuyecan** [comment]
暂定先这么处理：[#c727909](https://github.com/aliyun/aliyun-oss-android-sdk/commit/c727909f9a8bdc9256cde2323f0ffcb5943629f9)。谢谢！
