### ISSUE TITLE
好像okhttp包冲突

### ISSUE THREAD

**Issue by ccwls3290** [aliyun/aliyun-oss-android-sdk#18]
2.10的用了OKhttp 但是别的也用了okhttp怎么办？
compile 'com.facebook.fresco:imagepipeline-okhttp:0.8.0'
这个是fresco的库 然后报错
Error:Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jdk1.8.0_51\bin\java.exe'' finished with non-zero exit value 2
  请问应该怎么解决

但是compile 'com.aliyun.dpa:oss-android-sdk:1.4.0'这个和compile 'com.facebook.fresco:imagepipeline-okhttp:0.8.0'无错

**Comment by xuyecan** [comment]
更新到 compile 'com.facebook.fresco:imagepipeline-okhttp:0.9.0+' 呢？oss android sdk 2.1.0依赖了okhttp-2.7.0 和 okio 1.6.0，你看下是不是有冲突

**Comment by ccwls3290** [comment]
我更新了  我单独创建个项目：
只添加了
compile 'com.facebook.fresco:fresco:0.9.0+'
compile "com.facebook.fresco:imagepipeline-okhttp:0.9.0+"
然后添加oss库 
 还是不行

只要去掉
compile "com.facebook.fresco:imagepipeline-okhttp:0.9.0+"
就ok

**Comment by xuyecan** [comment]
你terminal里，在build.gradle文件所在目录，运行下`gradle dependencies`，看下对okhttp的依赖是不是有什么冲突？

**Comment by ccwls3290** [comment]
com.facebook.fresco:imagepipeline-okhttp:0.9.0+ -> 0.9.0
 +--- com.squareup.okhttp:okhttp:2.6.0
 |    \--- com.squareup.okio:okio:1.6.0
 +--- com.facebook.fresco:fbcore:0.9.0
 \--- com.facebook.fresco:imagepipeline:0.9.0 (*)

**Comment by xuyecan** [comment]
你能把工程clone下来，然后根据 https://github.com/aliyun/aliyun-oss-android-sdk#自行从源码编译jar包 编译一个jar包吗？最新的代码我已经把okhttp更新到okhttp3，更新后okhttp报名变了，应该不会再有冲突问题。
