### ISSUE TITLE
上传图片日志打印报错

### ISSUE THREAD

**Issue by YWD** [aliyun/aliyun-oss-android-sdk#185]
你好，OSS图片上传突然出现个奇怪的问题，希望可以看下。
![image](https://user-images.githubusercontent.com/8605395/62820437-d7b59180-bb96-11e9-844a-b83cd59f559e.png)
截图中打印日志是OSS文档中就这么写的，但是现在调试发现只要走这一步就会抛出异常被捕获。
下图为调试断点具体跳的位置，
![image](https://user-images.githubusercontent.com/8605395/62820432-c1a7d100-bb96-11e9-92f1-f954f3b61602.png)
具体在OSSRequestTask.java文件中。
请看一下问题。
还希望解释一下，这个打印只是打印一个属性值，为什么会引发异常？

**Comment by pushuhengyang** [comment]
经过测试 没有发现问题  可否贴下 异常提示
