### ISSUE TITLE
上传下载Callback缺少set方法

### ISSUE THREAD

**Issue by start141** [aliyun/aliyun-oss-android-sdk#19]
由于公司APP业务原因，我们的上传是开启Service进行上传的，期间可以会切换到不同的界面，在不同的界面callback的逻辑是不一样的(更新不同的界面什么的)，这就导致我们需要有callbadk的setter/getter方法，这事比较紧急，我们的文件存储已经全部迁移到阿里OSS上面了，以前的服务器已经关了，所以希望可以尽快提供callbadk的setter/getter方法，谢谢！

**Comment by xuyecan** [comment]
没太听明白你的需求。

callback是在调用上传、下载接口的时候以参数形式传进去的，如果有不同的callback，延迟到调用时决定不可以吗？

**Comment by start141** [comment]
意思是我需要在上传下载中途更换callback.

**Comment by xuyecan** [comment]
callback归属于任务，在调用的时候决定我觉得是合理的。归属给谁都不合适。

你说的需求，不可以把业务逻辑延迟到callback中决定吗？效果是一样的吧。比如，实现一个类implements callback接口，调用时候将它传入，然后持有它在不同场景中改变状态，等到回调它的时候，它根据自己的状态来决定做什么事情。

**Comment by start141** [comment]
你可以看一下其他项目，像android View的Onclicklistener也是一个callback，同样有setter/getter方法，同一个View我可以根据时机设置不同的listener，这是完全合理的，你说的什么归属我不赞同。

**Comment by start141** [comment]
你说的用延迟啊implements之类的就会把问题复杂化了。

**Comment by start141** [comment]
callback确实是归属于任务，但是我的意思是要提供一个给任务set callback的方法，新set的callback还是归属于之前的任务，不知道你是不是理解错我的意思了。

**Comment by xuyecan** [comment]
你打的比方不对，OnClickListener是监听器，持续性地对动作序列做响应，可以随时更换响应逻辑是合理的。

但SDK这里，是任务回调，在任务发起时就应该决定，以参数形式传入。任务完成时需要做什么处理，这个应该在回调里处理，而不是在外面决定更换什么回调。

你看下[okhttp](https://github.com/square/okhttp/wiki/Recipes)，或者[android-async-http](http://loopj.com/android-async-http/)。这些才是一样的场景，它们都是在任务发起时传入handler，发起后就换不了了。

**Comment by start141** [comment]
好吧，这个问题我已经用别的办法解决了。
