### ISSUE TITLE
各位有遇到这个问题吗？Broken pipe [ErrorMessage]: Broken pipe，求告知谢谢。

### ISSUE THREAD

**Issue by gassion** [aliyun/aliyun-oss-android-sdk#191]
上传文件有些文件是可以上传的，只有一个文件上传会报这个错误，com.alibaba.sdk.android.oss.ClientException: Broken pipe
[ErrorMessage]: Broken pipe
各位是怎么解决的，谢谢
![image](https://user-images.githubusercontent.com/14835591/66696674-8e9dcd00-ed00-11e9-897f-be04ea52604f.png)
![image](https://user-images.githubusercontent.com/14835591/66696683-a1180680-ed00-11e9-9149-a99d9662639b.png)
![image](https://user-images.githubusercontent.com/14835591/66696701-c0af2f00-ed00-11e9-83e5-e6483749b6c8.png)

**Comment by pushuhengyang** [comment]
> 上传文件有些文件是可以上传的，只有一个文件上传会报这个错误，com.alibaba.sdk.android.oss.ClientException: Broken pipe
> [ErrorMessage]: Broken pipe
> 各位是怎么解决的，谢谢
> ![image](https://user-images.githubusercontent.com/14835591/66696674-8e9dcd00-ed00-11e9-897f-be04ea52604f.png)
> ![image](https://user-images.githubusercontent.com/14835591/66696683-a1180680-ed00-11e9-9149-a99d9662639b.png)
> ![image](https://user-images.githubusercontent.com/14835591/66696701-c0af2f00-ed00-11e9-83e5-e6483749b6c8.png)

似乎是网络中断，可以参考https://www.jianshu.com/p/989ed0a2c3f9  ，可以把日志发出来看下，如果是网络原因，文件太大，可以考虑用分片上传或者断点续传。

**Comment by gassion** [comment]
> > 上传文件有些文件是可以上传的，只有一个文件上传会报这个错误，com.alibaba.sdk.android.oss.ClientException：管道破裂
> > [ErrorMessage]：管道破裂
> > 各位是怎么解决的，谢谢
> > ![图片](https://user-images.githubusercontent.com/14835591/66696674-8e9dcd00-ed00-11e9-897f-be04ea52604f.png)
> > ![图片](https://user-images.githubusercontent.com/14835591/66696683-a1180680-ed00-11e9-9149-a99d9662639b.png)
> > ![图片](https://user-images.githubusercontent.com/14835591/66696701-c0af2f00-ed00-11e9-83e5-e6483749b6c8.png)
> 
> 似乎是网络中断，可以参考https://www.jianshu.com/p/989ed0a2c3f9 ，可以把日志发出来看下，如果是网络原因，文件太大，可以考虑用分片上传或断点续传。

好的，非常感谢！我试试分片上传或断点续传。
