### ISSUE TITLE
使用最新的OSSFederationCredentialProvider中实现的方法getFederationToken不是在子线程调用吗？

### ISSUE THREAD

**Issue by nanfeifei** [aliyun/aliyun-oss-android-sdk#192]
您好，我这使用中碰到点问题，您能帮忙看一下吗，我查看最新的Demo，初始化OSS中获取token的代码看着像是在主线程执行的，你们那边Demo可以正常使用吗？我这边自己实现OSSFederationCredentialProvider类打断点这段执行的确在子线程，是需要我们把初始化OSS的代码放主线程吗？我看着您这边实现这个类按理说应该能实现token失效校验，如果token失效会重新获取token，如果你们在获取的这块在主线程的话我每一个调用OSS都必须写子线程里了，因为都可能重新获取token，获取你们那边有什么更好的办法吗？或者说token时效问题是需要由我们开发者来实现的

**Comment by nanfeifei** [comment]
我们的token信息获取是自己的接口及自己的字段命名，我写的类是跟这个差不多的，我目前是在实现的方法getFederationToken中获取当前线程拿到的是主线程，你们那个肯定也一样，按照你们Demo的写法你们这个类应该会报错的吧，你们那边显示图片列表的时候有什么好的方案吗？现在问题是如果我要通过token拿到图片地址再去显示图片因为请求token需要异步那我列表显示的图片肯定只会显示拿到token换到限时url的部分，除非是每一个请求都带一个请求标记，跟图片请求框架那样处理才行，但是这样的话太麻烦了

**Comment by pushuhengyang** [comment]
应该是子线程的，你可以在demo中看OSSRequestTask 这个类中call 方法  里面             OSSUtils.signRequest(message); 这一步 这是签名 ，里面获取token，此时是在子线程的；列表显示图片？不太明白你的意思，获取token之后拼接url是可以的 ，如果是说每次获取token需要更换，可以把token设置为全局。如果不想这么麻烦，可以把图片设置权限为公共读

**Comment by nanfeifei** [comment]
已解决，上传获取图片时是在子线程，但是获取私有图片地址的时候需要自己开子线程处理，我自己写的Provider类跟你们的没区别，只要实现你们的验证Token的抽象类就行，另外，创建一个私有的bucket，我们客户端能不能把公共权限文件上传进去，还是私有文件和公共文件必须使用两个bucket，麻烦您了

**Comment by pushuhengyang** [comment]
> 已解决，上传获取图片时是在子线程，但是获取私有图片地址的时候需要自己开子线程处理，我自己写的Provider类跟你们的没区别，只要实现你们的验证Token的抽象类就行，另外，创建一个私有的bucket，我们客户端能不能把公共权限文件上传进去，还是私有文件和公共文件必须使用两个bucket，麻烦您了

可以进行权限设置，可以参考https://help.aliyun.com/document_detail/100676.html?spm=a2c4g.11186623.6.659.1209630f2W5srn   ，object的权限会覆盖bucket权限 ；ios 文档不太全，可以参考demo中的例子使用OSSPutObjectACLRequest 来进行权限设置
