### ISSUE TITLE
App长时间处于后台后任何上传请求都没有任何回调

### ISSUE THREAD

**Issue by xuexiangjys** [aliyun/aliyun-oss-android-sdk#195]
App正常上传都没有问题，但是当app长时间处在后台，大概半小时的时候上传还是没有任何问题的，但是当处在后台1个多小时的时候，任何的上传操作都没有任何回调反馈【OSSCompletedCallback】，感觉貌似没有执行上传操作，日志调试打开了发现都很正常，没有任何异常输出，是不是什么对象被系统回收了？

**Comment by xuexiangjys** [comment]
补充一下，使用的sdk版本是2.9.2，初始化是这样的：
```
 public static OssService initOSS(Context context, OssSts ossSts) {
        OSSCredentialProvider credentialProvider = new OSSStsTokenCredentialProvider(ossSts.getAccessKeyId(), ossSts.getAccessKeySecret(), ossSts.getSecurityToken());
        ClientConfiguration conf = new ClientConfiguration();
        // 连接超时，默认15秒
        conf.setConnectionTimeout(60 * 1000);
        // socket超时，默认15秒
        conf.setSocketTimeout(60 * 1000);
        // 最大并发请求书，默认5个
        conf.setMaxConcurrentRequest(5);
        // 失败后最大重试次数，默认2次
        conf.setMaxErrorRetry(2);
        OSS oss = new OSSClient(context.getApplicationContext(), OSS_ENDPOINT, credentialProvider, conf);
        if (MyApp.isDebug()) {
            OSSLog.enableLog();
            return new OssService(oss, BUCKET_NAME_DEV);
        } else {
            return new OssService(oss, BUCKET_NAME);
        }
    }
```

**Comment by pushuhengyang** [comment]
> 补充一下，使用的sdk版本是2.9.2，初始化是这样的：
> 
> ```
>  public static OssService initOSS(Context context, OssSts ossSts) {
>         OSSCredentialProvider credentialProvider = new OSSStsTokenCredentialProvider(ossSts.getAccessKeyId(), ossSts.getAccessKeySecret(), ossSts.getSecurityToken());
>         ClientConfiguration conf = new ClientConfiguration();
>         // 连接超时，默认15秒
>         conf.setConnectionTimeout(60 * 1000);
>         // socket超时，默认15秒
>         conf.setSocketTimeout(60 * 1000);
>         // 最大并发请求书，默认5个
>         conf.setMaxConcurrentRequest(5);
>         // 失败后最大重试次数，默认2次
>         conf.setMaxErrorRetry(2);
>         OSS oss = new OSSClient(context.getApplicationContext(), OSS_ENDPOINT, credentialProvider, conf);
>         if (MyApp.isDebug()) {
>             OSSLog.enableLog();
>             return new OssService(oss, BUCKET_NAME_DEV);
>         } else {
>             return new OssService(oss, BUCKET_NAME);
>         }
>     }
> ```
> 
> 上传使用的是mOss.asyncPutObject(put, completedCallback)方法

长时间后台状态，确实可能某些对象，变量会被系统回收，这种状况并没有考虑，太极端了

**Comment by xuexiangjys** [comment]
那有没有什么补救措施呢？ @pushuhengyang

**Comment by pushuhengyang** [comment]
> 那有没有什么补救措施呢？ @pushuhengyang

可以看下日志信息 ，看看是哪里的问题

**Comment by xuexiangjys** [comment]
@pushuhengyang 出问题的时候，没有打印任何信息，只有开头几行设备信息。我前几天试了好几次，理论上这个应该是必现的，你可以试一下
```
2019-10-30 12:29:09.317 26690-26818/com.XXX.XXXX I/OSS-Android-SDK: [INFO]: =====[device info]=====
    [INFO]: android_version：7.0
    [INFO]: mobile_model：HUAWEI MLA-AL10
    [INFO]: operator_name：CTCC
    [INFO]: network_state：connected
    [INFO]: network_type：WIFI 
```

**Comment by xuexiangjys** [comment]
最后发现是SDK内部crash了，至于crash的原因如下图所示，应该还是token失效的问题，但是不知道为什么会导致崩溃...目前暂时是重写OSSFederationCredentialProvider解决了。
![image](https://user-images.githubusercontent.com/15059629/69530178-92ce3300-0fac-11ea-9cee-06a7b1478f0d.png)
