### ISSUE TITLE
分片上传后，片的文件大小为0，下载后102k文件长度为0

### ISSUE THREAD

**Issue by guohuan1990** [aliyun/aliyun-oss-android-sdk#197]
分片上传文件40K大小，上传分片就一片，返回值中Content-length=0，

**Comment by pushuhengyang** [comment]
> 分片上传文件40K大小，上传分片就一片，返回值中Content-length=0，

上传的返回值确实是0  下载文件不应该是0 可否提供日志，看看问题在哪？

**Comment by guohuan1990** [comment]
public static AliOssMultiHelper.MultiPutCallback multipartUpload(Context context, final AliOSSRoleEntry entry, final File file) {

        // Endpoint以杭州为例，其它Region请按实际情况填写。
        String endpoint = entry.endpoint;
        // 阿里云主账号AccessKey拥有所有API的访问权限，风险很高。强烈建议您创建并使用RAM账号进行API访问或日常运维，请登录 https://ram.console.aliyun.com 创建RAM账号。
        String accessKeyId = entry.accessKeyId;
        String accessKeySecret = entry.accessKeySecret;
        String bucketName = entry.bucket;
        // <yourObjectName>表示上传文件到OSS时需要指定包含文件后缀在内的完整路径，例如abc/efg/123.jpg。
        String objectName = entry.objectPrefix + file.getName();


        ClientConfiguration conf = new ClientConfiguration();
        conf.setHttpDnsEnable(false);
        OSS mOSS = new OSSClient(context, entry.endpoint, newOSSStsTokenCredentialProvider(entry.accessKeyId, entry.accessKeySecret, entry.securityToken), conf);


        //初始化分片上传。
        //InitiateMultipartUploadRequest用于指定上传文件的名称以及上传文件所属的存储空间的名称。
        InitiateMultipartUploadRequest init = new InitiateMultipartUploadRequest(bucketName, objectName);
        InitiateMultipartUploadResult initResult = null;
        try {
            initResult = mOSS.initMultipartUpload(init);
        } catch (ClientException e) {
            e.printStackTrace();
        } catch (ServiceException e) {
            e.printStackTrace();
        }
        //initResult返回的结果中包含UploadId，UploadId用于唯一标识本次Multipart Upload事件。
        String uploadId = initResult.getUploadId();
        List<PartETag> partETags = new ArrayList<PartETag>();

        // 计算文件有多少个分片。
        long partSize = 1 * 100 * 1024L;   // 1MB
        File sampleFile = file;
        long fileLength = sampleFile.length();
        int partCount = (int) (fileLength / partSize);


        if (fileLength % partSize != 0) {
            partCount++;
        }


        //分片上传。
        for (int i = 1; i <= partCount; i++) {
            byte[] data = new byte[(int) partSize];
            UploadPartRequest uploadPart = new UploadPartRequest();
            uploadPart.setBucketName(bucketName);
            uploadPart.setObjectKey(objectName);
            uploadPart.setUploadId(uploadId);
            //上传的Part对应的part number从1开始标识。
            uploadPart.setPartNumber(i);
            uploadPart.setPartContent(data);
            try {
                UploadPartResult uploadPartResult = mOSS.uploadPart(uploadPart);
                partETags.add(new PartETag(i, uploadPartResult.getETag()));
                LOG.logE("UploadPart Success:position="+i+"//uploadPartResult.getETeg"+uploadPartResult.getETag());
            } catch (ClientException e) {
                e.printStackTrace();
                LOG.logE("UploadPart ClientException"+e.getMessage());
            } catch (ServiceException e) {
                e.printStackTrace();
                LOG.logE("UploadPart ServiceException"+e.getErrorCode());
            }

        }




        //完成分片上传。
        final CompleteMultipartUploadRequest completeRequest = new CompleteMultipartUploadRequest(bucketName, objectName, uploadId, partETags);

        //上传回调。完成分片上传请求时可以设置CALLBACK_SERVER参数，请求完成后会向指定的Server Address发送回调请求。可通过返回结果的completeResult.getServerCallbackReturnBody()查看servercallback结果。
        completeRequest.setCallbackParam(new HashMap<String, String>() {
            {
              JSONObject jsonObject = new JSONObject();
                try {
                    jsonObject.put("mimeType", ("application/x-compressed"));
                    jsonObject.put("size", file.length());
                    jsonObject.put("bucket", entry.bucket);
                    jsonObject.put("object", completeRequest.getObjectKey());
                } catch (JSONException e) {
                    e.printStackTrace();
                }
                put("callbackUrl", entry.callback);
                put("callbackBody", jsonObject.toString());
                put("callbackBodyType", "application/json");
            }
        });

        //
//        completeRequest.setCRC64(OSSRequest.CRC64Config.YES);


        MultiPutCallback multiPutCallback = new MultiPutCallback();

        LOG.logD("Complete MultipartUpload start  ");
//        OSSAsyncTask<CompleteMultipartUploadResult> completeResult = mOSS.asyncCompleteMultipartUpload(completeRequest, multiPutCallback);
        try {
            CompleteMultipartUploadResult completeMultipartUploadResult = mOSS.completeMultipartUpload(completeRequest);
            multiPutCallback.result=completeMultipartUploadResult;
            multiPutCallback.request=completeRequest;

        } catch (ClientException e) {
            e.printStackTrace();
            multiPutCallback.clientException=e;
        } catch (ServiceException e) {
            e.printStackTrace();
            multiPutCallback.serviceException=e;
        }


        return multiPutCallback;

    }

    final public static class MultiPutCallback implements OSSCompletedCallback<CompleteMultipartUploadRequest, CompleteMultipartUploadResult> {


        public ClientException clientException;
        public ServiceException serviceException;
        public CompleteMultipartUploadRequest request;
        public CompleteMultipartUploadResult result;




        @Override
        public void onSuccess(CompleteMultipartUploadRequest request, CompleteMultipartUploadResult result) {
            this.request = request;
            this.result = result;
        }

        @Override
        public void onFailure(CompleteMultipartUploadRequest request, ClientException clientException, ServiceException serviceException) {
            this.request = request;
            this.clientException = clientException;
            this.serviceException = serviceException;
        }
    }

**Comment by guohuan1990** [comment]
以上是分片代码，文件可以上传，下载后是102k，并不是文件的真是大小。

**Comment by pushuhengyang** [comment]
> 以上是分片代码，文件可以上传，下载后是102k，并不是文件的真是大小。

文档中的有问题  
![image](https://user-images.githubusercontent.com/15009447/68454039-596a9900-0232-11ea-9428-43be85d9c8f6.png)
需要填充数据的  抱歉了   这里会修改的  给你一个参考
![截屏2019-11-08下午2 18 29](https://user-images.githubusercontent.com/15009447/68454120-a64e6f80-0232-11ea-9449-e98425c5681e.png)

**Comment by pushuhengyang** [comment]
@guohuan1990   建议直接用asyncMultipartUpload  更简洁一些

**Comment by pushuhengyang** [comment]
> 以上是分片代码，文件可以上传，下载后是102k，并不是文件的真是大小。


![](https://user-images.githubusercontent.com/15009447/68454039-596a9900-0232-11ea-9428-43be85d9c8f6.png)
这里只是做了简单的初始化数据，需要填充具体数据 ，需要自己做，  文档中没有写  稍后会修改下。

**Comment by pushuhengyang** [comment]
> 以上是分片代码，文件可以上传，下载后是102k，并不是文件的真是大小。

![截屏2019-11-08下午2 42 19](https://user-images.githubusercontent.com/15009447/68455289-fa0e8800-0235-11ea-9775-b0e2c0c809ce.png)
可以做个参考 ，具体需要自己去修改

**Comment by guohuan1990** [comment]
感谢大神，问题已解决  确实是分片byte[]没有拷贝数据

**Comment by pushuhengyang** [comment]
> 感谢大神，问题已解决 确实是分片byte[]没有拷贝数据

解决就好 文档的问题  那你把问题关了吧
