### ISSUE TITLE
上传失败的概率很高

### ISSUE THREAD

**Issue by start141** [aliyun/aliyun-oss-android-sdk#20]
不知道是什么原因，今天上传文件失败率很高，超过百分之五十的失败率。

clientException != null，clientException.getMessage()为null
serviceException != null

**Comment by start141** [comment]
有没有什么方法可以定位到真正的错误位置？

**Comment by start141** [comment]
谢谢

**Comment by xuyecan** [comment]
有什么IM工具可以联系你吗，这个问题看起来要仔细沟通才行。

**Comment by start141** [comment]
可以啊，你加我企鹅，我的邮箱号就是了

**Comment by xuyecan** [comment]
已有结论，是网络问题所致。
