### ISSUE TITLE
手机飞行模式时，调用断点续传接口上传文件，出现的异常要如何处理？

### ISSUE THREAD

**Issue by fourmigh** [aliyun/aliyun-oss-android-sdk#206]
没有网络连接的情况下（比如飞行模式）调用了断点续传接口
1、只看到SDK输出了“java.net.UnknownHostException: Unable to resolve host”之类的日志，却没有onFailure回调
2、这时再打开网络，虽然连上了网，估计已经超过重试次数，也没开始上传

这种情况下，在不重启应用的情况下，该如何处理以便开始上传文件？

**Comment by luckykellan** [comment]
请问解决了吗，我也碰到同样的问题
