### ISSUE TITLE
请教一下~为什么我调用了上传文件的接口，OSSCompletedCallback没有回调onSuccess

### ISSUE THREAD

**Issue by CatLoli** [aliyun/aliyun-oss-android-sdk#209]
putObjectRequest.setProgressCallback(new OSSProgressCallback<PutObjectRequest>() {
            @Override
            public void onProgress(PutObjectRequest request, long currentSize, long totalSize) {
//                KLog.d("阿里云--------上传中" + "currentSize: " + currentSize + " totalSize: " + totalSize);
                double progress = currentSize * 1.0 / totalSize * 100.f;
//                KLog.d("阿里云--------上传中" + "上传进度-----" + progress);
                if (progress == 100) {
                    KLog.d("阿里云---------" +"进度回调---上传完成---" + request);
                }
            }
        });
        OSSAsyncTask<PutObjectResult> asyncTask = mOss.asyncPutObject(putObjectRequest, new OSSCompletedCallback<PutObjectRequest, PutObjectResult>() {
            @Override
            public void onSuccess(PutObjectRequest request, PutObjectResult result) {
                KLog.d("阿里云---------" + "上传成功-----" + result);
            }

            @Override
            public void onFailure(PutObjectRequest request, ClientException clientException, ServiceException serviceException) {
                KLog.e("阿里云---------" + "上传失败-------");
            }
        });
以上就是上传的东西，我调用过程中，onProgress是正常回调的，但是OSSCompletedCallback的onSuccess一次都没有掉过，onFailure会被调用，这是为啥呀~

**Comment by pushuhengyang** [comment]
@CatLoli    按道理不应该  这边验证是可以的  ，可以尝试单次测试，看是否会调用，也可以下载我们的示例代码测试，这边看你的代码 没什么大问题，可以打开ossLog  看下日志。

**Comment by CatLoli** [comment]
解决了，我忘记打开ossLog了，打开那个日志就有key的问题，必须要打开ossLog才会有相关日志输出
