### ISSUE TITLE
断点续传失败

### ISSUE THREAD

**Issue by liujunhg** [aliyun/aliyun-oss-android-sdk#21]
已在阿里云的工单系统中沟通，非必现bug，之前也出现过这种情况
有一个文件无法上传，删除记录断点续传文件后，能够正常上传
失败日志如下：
03-15 10:32:02.034 19642-19829/com.camory.cloudcamera.china W/System.err: java.io.IOException: Invalid int: "null"
03-15 10:32:02.034 19642-19829/com.camory.cloudcamera.china W/System.err:     at com.alibaba.sdk.android.oss.internal.ResponseParsers$ListPartsResponseParser.parse(ResponseParsers.java:275)
03-15 10:32:02.034 19642-19829/com.camory.cloudcamera.china W/System.err:     at com.alibaba.sdk.android.oss.internal.ResponseParsers$ListPartsResponseParser.parse(ResponseParsers.java:262)
03-15 10:32:02.034 19642-19829/com.camory.cloudcamera.china W/System.err:     at com.alibaba.sdk.android.oss.network.OSSRequestTask.call(OSSRequestTask.java:314)
03-15 10:32:02.034 19642-19829/com.camory.cloudcamera.china W/System.err:     at com.alibaba.sdk.android.oss.network.OSSRequestTask.call(OSSRequestTask.java:54)
03-15 10:32:02.034 19642-19829/com.camory.cloudcamera.china W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
03-15 10:32:02.034 19642-19829/com.camory.cloudcamera.china W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
03-15 10:32:02.034 19642-19829/com.camory.cloudcamera.china W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
03-15 10:32:02.034 19642-19829/com.camory.cloudcamera.china W/System.err:     at java.lang.Thread.run(Thread.java:818)
03-15 10:32:02.034 19642-19829/com.camory.cloudcamera.china W/System.err: Caused by: java.lang.NumberFormatException: Invalid int: "null"
03-15 10:32:02.035 19642-19829/com.camory.cloudcamera.china W/System.err:     at java.lang.Integer.invalidInt(Integer.java:138)
03-15 10:32:02.035 19642-19829/com.camory.cloudcamera.china W/System.err:     at java.lang.Integer.parseInt(Integer.java:358)
03-15 10:32:02.035 19642-19829/com.camory.cloudcamera.china W/System.err:     at java.lang.Integer.parseInt(Integer.java:334)
03-15 10:32:02.035 19642-19829/com.camory.cloudcamera.china W/System.err:     at java.lang.Integer.valueOf(Integer.java:525)
03-15 10:32:02.035 19642-19829/com.camory.cloudcamera.china W/System.err:     at com.alibaba.sdk.android.oss.internal.ResponseParsers.parseListPartsResponseXML(ResponseParsers.java:329)
03-15 10:32:02.035 19642-19829/com.camory.cloudcamera.china W/System.err:     at com.alibaba.sdk.android.oss.internal.ResponseParsers.access$400(ResponseParsers.java:49)
03-15 10:32:02.035 19642-19829/com.camory.cloudcamera.china W/System.err:     at com.alibaba.sdk.android.oss.internal.ResponseParsers$ListPartsResponseParser.parse(ResponseParsers.java:267)
03-15 10:32:02.035 19642-19829/com.camory.cloudcamera.china W/System.err: 	... 7 more
03-15 10:32:02.070 19642-19829/com.camory.cloudcamera.china W/System.err: java.io.IOException: Invalid int: "null"
03-15 10:32:02.071 19642-19829/com.camory.cloudcamera.china W/System.err:     at com.alibaba.sdk.android.oss.internal.ResponseParsers$ListPartsResponseParser.parse(ResponseParsers.java:275)
03-15 10:32:02.071 19642-19829/com.camory.cloudcamera.china W/System.err:     at com.alibaba.sdk.android.oss.internal.ResponseParsers$ListPartsResponseParser.parse(ResponseParsers.java:262)
03-15 10:32:02.071 19642-19829/com.camory.cloudcamera.china W/System.err:     at com.alibaba.sdk.android.oss.network.OSSRequestTask.call(OSSRequestTask.java:314)
03-15 10:32:02.071 19642-19829/com.camory.cloudcamera.china W/System.err:     at com.alibaba.sdk.android.oss.network.OSSRequestTask.call(OSSRequestTask.java:328)
03-15 10:32:02.071 19642-19829/com.camory.cloudcamera.china W/System.err:     at com.alibaba.sdk.android.oss.network.OSSRequestTask.call(OSSRequestTask.java:54)
03-15 10:32:02.071 19642-19829/com.camory.cloudcamera.china W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
03-15 10:32:02.071 19642-19829/com.camory.cloudcamera.china W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
03-15 10:32:02.071 19642-19829/com.camory.cloudcamera.china W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
03-15 10:32:02.071 19642-19829/com.camory.cloudcamera.china W/System.err:     at java.lang.Thread.run(Thread.java:818)
03-15 10:32:02.071 19642-19829/com.camory.cloudcamera.china W/System.err: Caused by: java.lang.NumberFormatException: Invalid int: "null"
03-15 10:32:02.071 19642-19829/com.camory.cloudcamera.china W/System.err:     at java.lang.Integer.invalidInt(Integer.java:138)
03-15 10:32:02.072 19642-19829/com.camory.cloudcamera.china W/System.err:     at java.lang.Integer.parseInt(Integer.java:358)
03-15 10:32:02.072 19642-19829/com.camory.cloudcamera.china W/System.err:     at java.lang.Integer.parseInt(Integer.java:334)
03-15 10:32:02.072 19642-19829/com.camory.cloudcamera.china W/System.err:     at java.lang.Integer.valueOf(Integer.java:525)
03-15 10:32:02.072 19642-19829/com.camory.cloudcamera.china W/System.err:     at com.alibaba.sdk.android.oss.internal.ResponseParsers.parseListPartsResponseXML(ResponseParsers.java:329)
03-15 10:32:02.072 19642-19829/com.camory.cloudcamera.china W/System.err:     at com.alibaba.sdk.android.oss.internal.ResponseParsers.access$400(ResponseParsers.java:49)
03-15 10:32:02.072 19642-19829/com.camory.cloudcamera.china W/System.err:     at com.alibaba.sdk.android.oss.internal.ResponseParsers$ListPartsResponseParser.parse(ResponseParsers.java:267)
03-15 10:32:02.072 19642-19829/com.camory.cloudcamera.china W/System.err: 	... 8 more

**Comment by xuyecan** [comment]
已在2.0.2版本修复此问题。
