### ISSUE TITLE
上传时提示  No address associated with hostname

### ISSUE THREAD

**Issue by maoruibin** [aliyun/aliyun-oss-android-sdk#212]
使用最新的 sdk ，设置好了关键信息，另外我使用的是主账号、密码登录，即使用 OSSPlainTextAKSKCredentialProvider 生成 CredentialProvider 。
我的 bucket 是 picplus，然后执行上传时，提示`No address associated with hostname`  我看 url 会在上传时自拼接我的 bucket name，这个怎么解决一下，盼回复。

![](https://picplus.oss-cn-beijing.aliyuncs.com/20200312100258.png)

**Comment by steve-wanglin** [comment]
问一下，你是咋觉得这个问题的吖？
