### ISSUE TITLE
设备时间与自然时间不一致导致OSSFederationCredentialProvider失常

### ISSUE THREAD

**Issue by wszf** [aliyun/aliyun-oss-android-sdk#22]
现象：
1.上传序列与token获取先后顺序毫无关联，有时先token有时先上传
2.不管啊是异步上传还是同步上传，状况如1
3.即使采用同步的方式先获取token，然后设置OSSStsTokenCredentialProvider，最后在上传，情况如1

报错如下：
`RawMessage：<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html>
<head><title>400 Bad Request</title></head>
<body bgcolor="white">
<h1>400 Bad Request</h1>
<p>Your browser sent a request that this server could not understand.<hr/>Powered by AliyunOSS</body>
</html>`

**Comment by xuyecan** [comment]
1. Token是可以复用的，SDK调用回调获得一次后，在有效期内会多次使用，所以出现你观察到的现象。
2. 如果是时间问题，SDK会根据服务端返回403 RequestTimeTooSkewed，采用服务端返回响应标记的标准时间，校准自己的时间基准值，然后采用新的时间进行重试。这个错误看起来并不是这个问题。可以开启调试log观察一下发出的请求头是什么。
