### ISSUE TITLE
使用new OSSClient();方法创建OSSClient怎么会卡住主线程啊？

### ISSUE THREAD

**Issue by FrankyLee-dev** [aliyun/aliyun-oss-android-sdk#223]
OSSCredentialProvider credentialProvider = new OSSStsTokenCredentialProvider(accessKeyId, accessKeySecret, securityToken);

        // init conf
        ClientConfiguration conf = ConfigUtils.initAuthConfig(configuration);

        mOSS = new OSSClient(mContext, endPoint, credentialProvider, conf);
这里new OSSClient很慢并且卡住了主线程

**Comment by shaobin0604** [comment]
怀疑是 #220 这个问题导致的

**Comment by frankyLHJ** [comment]
> 怀疑是 #220 #183 #155 这个问题导致的

debug下会卡住但是不影响使用。打包后居然就不会卡住主线程了，不清楚到底什么原因。

**Comment by wushuai1415** [comment]
OSS初始化是会调用InetAddress.getByName检查endpoint的host是否为ip，访问DNS服务器慢时会卡住主线程
