### ISSUE TITLE
请问一下自签名模式的细节

### ISSUE THREAD

**Issue by Lujango** [aliyun/aliyun-oss-android-sdk#23]
String endpoint = "http://oss-cn-hangzhou.aliyuncs.com";

credentialProvider = new OSSCustomSignerCredentialProvider() {
    @Override
    public String signContent(String content) {
        return "OSS " + AccessKeyId + ":" + base64(hmac-sha1(AccessKeySecret, content));
    }
};

OSS oss = new OSSClient(getApplicationContext(), endpoint, credentialProvider);
我想试试本地算法实现，
把里面的两个key设置成自己的key 上传会报错：SignatureDoesNotMatch
用明文的new OSSPlainTextAKSKCredentialProvider("<accessKeyId>", "<accessKeySecret>");就没有问题

**Comment by xuyecan** [comment]
可以参考OSSUtils类下的sign函数：[这里](https://github.com/aliyun/aliyun-oss-android-sdk/blob/master/oss-android-sdk/src/main/java/com/alibaba/sdk/android/oss/common/utils/OSSUtils.java)。

可以调用，打印一下，对比自己实现的，看下差异。

**Comment by Lujango** [comment]
可以了，看来是加密函数的问题，我理解的步骤没有错，昨天去工单里面搞了半天。。。。
还是这里效率高，谢谢了。
