### ISSUE TITLE
Could not find oss-android-sdk.jar

### ISSUE THREAD

**Issue by chinamingsss** [aliyun/aliyun-oss-android-sdk#237]
Could not find oss-android-sdk.jar (com.aliyun.dpa:oss-android-sdk:2.9.5).
Searched in the following locations:

**Comment by yang464231025** [comment]
我也是突然出现这个问题，一脸懵逼

**Comment by tianbaojun** [comment]
same problem

**Comment by chinamingsss** [comment]
是啊，不知道为什么，前几天还好好的，今天突然不行了，愁死人，换成2.7.0就行，你们可以试试

**Comment by chinamingsss** [comment]
最后一个release版本是2.9.4把2.9.5改成2.9.4就可以了

**Comment by dabutaizha** [comment]
> 最后一个release版本是2.9.4把2.9.5改成2.9.4就可以了

现在好像也不行了

**Comment by chinamingsss** [comment]
我的可以啊，不行了吗？

**Comment by yang464231025** [comment]
> > 最后一个release版本是2.9.4把2.9.5改成2.9.4就可以了
> 
> 现在好像也不行了

改成2.7.0，亲测可以了

**Comment by chinamingsss** [comment]
我的改成2.9.4是可以的，版本改太低会不会有问题呢

**Comment by Quy520** [comment]
> > > 最后一个release版本是2.9.4把2.9.5改成2.9.4就可以了
> > 
> > 
> > 现在好像也不行了
> 
> 改成2.7.0，亲测可以了

的确可以

**Comment by Quy520** [comment]
> 我的改成2.9.4是可以的，版本改太低会不会有问题呢

不会

**Comment by Quy520** [comment]
> > > > 最后一个release版本是2.9.4把2.9.5改成2.9.4就可以了
> > > 
> > > 
> > > 现在好像也不行了
> > 
> > 
> > 改成2.7.0，亲测可以了
> 
> 的确可以但是这个好像版本太低老 有问题

**Comment by Quy520** [comment]
> > 我的改成2.9.4是可以的，版本改太低会不会有问题呢
> 
> 2.9.4 不会

**Comment by wushuai1415** [comment]
由于网络问题导致发布2.9.5上传一半发生错误，库里只有部分文件最新版本却指向了2.9.5。现已将2.9.5版本删除。使用OSS时请最好指定版本

**Comment by xiaochedexinyang1** [comment]
> 由于网络问题导致发布2.9.5上传一半发生错误，库里只有部分文件最新版本却指向了2.9.5。现已将2.9.5版本删除。使用OSS时请最好指定版本

还是不行 ，是有缓存吗

**Comment by wushuai1415** [comment]
@xiaochedexinyang1 应该是的，现在2.9.5已经删了，请使用2.9.4

**Comment by LuffyBySunny** [comment]
> @xiaochedexinyang1 应该是的，现在2.9.5已经删了，请使用2.9.4

上面说的版本试了一遍，都不行

**Comment by wushuai1415** [comment]
@LuffyBySunny 如果是报和2.9.5相关的错误，请尝试清除缓存重新拉取
