### ISSUE TITLE
Failed to resolve: oss-android-sdk

### ISSUE THREAD

**Issue by wenideveloper** [aliyun/aliyun-oss-android-sdk#241]
Could not find oss-android-sdk.jar (com.aliyun.dpa:oss-android-sdk:2.9.5).
Searched in the following locations:
https://jcenter.bintray.com/com/aliyun/dpa/oss-android-sdk/2.9.5/oss-android-sdk-2.9.5.jar

**Comment by wushuai1415** [comment]
由于网络问题导致发布2.9.5上传一半发生错误，库里只有部分文件最新版本却指向了2.9.5。现已将2.9.5版本删除。使用OSS时请最好指定版本

**Comment by ScarlettBinBinBin** [comment]
死妈垃圾骗钱玩意，马云必将下地狱，全体阿里废物技术陪他一起埋葬吧！！！
