### ISSUE TITLE
更新一直失败

### ISSUE THREAD

**Issue by chengmenghuiAndroid** [aliyun/aliyun-oss-android-sdk#244]
Could not find oss-android-sdk.jar (com.aliyun.dpa:oss-android-sdk:2.9.5).
Searched in the following locations:
    https://jcenter.bintray.com/com/aliyun/dpa/oss-android-sdk/2.9.5/oss-android-sdk-2.9.5.jar

**Comment by wushuai1415** [comment]
请尝试清除缓存，重新拉取

**Comment by wangxuanlong** [comment]
> 请尝试清除缓存，重新拉取

指定2.9.4还是报一样的错误

**Comment by wushuai1415** [comment]
@wangxuanlong 如果还是报和2.9.5相关的错误应该是缓存没有清掉吧

**Comment by good-good-study** [comment]
升级了Androidstudio 4.1之后， 项目无法运行，报错信息 跟楼主是一模一样的。
Could not find oss-android-sdk-2.9.5.jar (com.aliyun.dpa:oss-android-sdk:2.9.5).
Searched in the following locations:
         https://jcenter.bintray.com/com/aliyun/dpa/oss-android-sdk/2.9.5/oss-android-sdk-2.9.5.jar

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

**Comment by xiehui999** [comment]
+1
