### ISSUE TITLE
升级了Androidstudio 4.1之后， 项目无法运行

### ISSUE THREAD

**Issue by good-good-study** [aliyun/aliyun-oss-android-sdk#245]
升级了Androidstudio 4.1之后， 项目无法运行，报错信息。清除缓存也没用，还是报错。
Could not find oss-android-sdk-2.9.5.jar (com.aliyun.dpa:oss-android-sdk:2.9.5).
Searched in the following locations:
https://jcenter.bintray.com/com/aliyun/dpa/oss-android-sdk/2.9.5/oss-android-sdk-2.9.5.jar

Possible solution:

Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

**Comment by wushuai1415** [comment]
gradlew build --refresh-dependencies更新一下依赖

**Comment by good-good-study** [comment]
还是不行

**Comment by good-good-study** [comment]
> gradlew build --refresh-dependencies更新一下依赖
还是不行

**Comment by good-good-study** [comment]
已解决，更新了一下其他sdk的版本就好了，真挺无语的

**Comment by xiehui999** [comment]
+1
