### ISSUE TITLE
设置生命周期规则失败

### ISSUE THREAD

**Issue by shaoguanglin** [aliyun/aliyun-oss-android-sdk#254]
sdk：2.9.4
设置生命周期规则报错：
error: <?xml version="1.0" encoding="UTF-8"?>
    <Error>
      <Code>MalformedXML</Code>
      <Message>The XML you provided was not well-formed or did not validate against our published schema.</Message>
      <RequestId>5FACE8B26C237B34362889D3</RequestId>
      <HostId>xxxxxx</HostId>
      <ErrorDetail>Action is missing</ErrorDetail>
    </Error>

但是我对比官方的文档列子 写的 不知道是哪里出了问题啊！！

下面是我的设置规则代码：
   PutBucketLifecycleRequest putBucketLifecycleRequest = new PutBucketLifecycleRequest();
                    putBucketLifecycleRequest.setBucketName(bucketName);

                    BucketLifecycleRule rule1 = new BucketLifecycleRule();

                    rule1.setIdentifier(id);
                    rule1.setPrefix(prefix);
                    rule1.setDays(String.valueOf(effectDays));
                    rule1.setStatus(true);
                    rule1.setArchiveDays(String.valueOf(effectDays-1));

//                    rule1.setIADays(String.valueOf(effectDays-1));
//                    rule1.setMultipartDays(String.valueOf(effectDays-1));
                    list.add(rule1);
                    putBucketLifecycleRequest.setLifecycleRules(list);

prefix 比如是 ttt1/这样的

**Comment by wushuai1415** [comment]
你的代码在我这里没有问题，debug看一下RequestMessage.putBucketLifecycleRequestBodyMarshall()里xmlBody是什么

**Comment by shaoguanglin** [comment]
找到原因了！因为我把之前的规则查到后，设置新规则的时候也加入进去了 。。。。抱歉 打扰了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "wushuai1415"<notifications@github.com&gt;; 
发送时间: 2020年11月12日(星期四) 下午5:25
收件人: "aliyun/aliyun-oss-android-sdk"<aliyun-oss-android-sdk@noreply.github.com&gt;; 
抄送: "s~ing"<401374976@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [aliyun/aliyun-oss-android-sdk] 设置生命周期规则失败 (#254)





 
你的代码在我这里没有问题，debug看一下RequestMessage.putBucketLifecycleRequestBodyMarshall()里xmlBody是什么
