### ISSUE TITLE
能在sample 来一个SST鉴权模式的例子嘛

### ISSUE THREAD

**Issue by huizaiyo** [aliyun/aliyun-oss-android-sdk#26]
SST鉴权模式搞不定，，，

**Comment by xuyecan** [comment]
可以参考这个demo： https://help.aliyun.com/document_detail/31941.html  ，里头用的就是sts鉴权模式。

**Comment by huizaiyo** [comment]
@xuyecan 好的 灰常感谢O(∩_∩)O~
