### ISSUE TITLE
OSSAuthCredentialsProvider getFederationToken 异常没有回调

### ISSUE THREAD

**Issue by shaohui93** [aliyun/aliyun-oss-android-sdk#260]
当getFederationToken 方法出现异常时 不会走里面当回调 oss.asyncPutObject(put, object : OSSCompletedCallback<PutObjectRequest?, PutObjectResult> {}

**Comment by shaohui93** [comment]
![image](https://user-images.githubusercontent.com/24472038/101369337-25552200-38e3-11eb-8532-ccebe7649671.png)
断点走了onFailure这个方法，但是上层收不到回调，不知道咋回事。。

**Comment by wushuai1415** [comment]
哪个版本的sdk

**Comment by shaohui93** [comment]
sdk版本 2.9.2

**Comment by shaohui93** [comment]
> 哪个版本的sdk

sdk版本 2.9.2，直接把手机的网络关掉，可以复现这个问题，会走上图的异常回调，但是不会走到oss?.asyncPutObject 这个方法设置的异常回调里，不知道为什么

**Comment by wushuai1415** [comment]
@shaohui93 我这不能复现，你看一下completedCallback和你传进来的是一个对象吗

**Comment by shaohui93** [comment]
> @shaohui93 我这不能复现，你看一下completedCallback和你传进来的是一个对象吗

![image](https://user-images.githubusercontent.com/24472038/101453635-9c81c900-396a-11eb-8b40-7da890cfbb4e.png)
就是调用这个方法传进去的completedCallback，应该没啥问题，用kotlin写的，不知道有没有影响

**Comment by wushuai1415** [comment]
@shaohui93 clientException和serviceException的类型加?试一下
override fun onFailure(request: PutObjectRequest?, clientException: ClientException?, serviceException: ServiceException?) {
}

**Comment by shaohui93** [comment]
> @shaohui93 clientException和serviceException的类型加?试一下
> override fun onFailure(request: PutObjectRequest?, clientException: ClientException?, serviceException: ServiceException?) {
> }
可以了，现在断网会走到异常到回调上去了，感谢🙏

**Comment by shaohui93** [comment]
> @shaohui93 clientException和serviceException的类型加?试一下
> override fun onFailure(request: PutObjectRequest?, clientException: ClientException?, serviceException: ServiceException?) {
> }

可以了，现在断网会走到异常到回调上去了，感谢🙏
