### ISSUE TITLE
下载任务的失败回调OSSCompletedCallback.onFailure(x,x)入参有空指针

### ISSUE THREAD

**Issue by RealMoMo** [aliyun/aliyun-oss-android-sdk#263]
特意断网情况下，进行文件下载，原有程序存在onFailure的回调，做自己的相应操作。但发现没有继续执行下去，且程序没有crash。后续加log发现参数ServiceException对象为null,但使用该对应对应获取相应信息logcat没有报出nullpointexpection
![image](https://user-images.githubusercontent.com/22723389/104157909-17854600-5427-11eb-9bc6-806219114316.png)
![image](https://user-images.githubusercontent.com/22723389/104157947-3683d800-5427-11eb-8802-98db264ead8b.png)

**Comment by RealMoMo** [comment]
```
@Override
            public void onFailure(GetObjectRequest request, ClientException clientException,
                                  ServiceException serviceException) {
                if (listener != null) {
                    Log.w("rota","resume onFailure:");
                    Log.w("rota","clientException == null:"+(clientException == null));
                    Log.w("rota","serviceException == null:"+(serviceException == null));
                    listener.onFailureDownLoad(clientException, serviceException);
                }
                Log.w("rota", "resume fail download---service exception:"+serviceException.toString());

                clientException.printStackTrace();
                serviceException.printStackTrace();
                Log.w("rota", "resume fail download---finished:");

            }
```

输出rota标签的logcat
2021-01-11 16:00:49.007 19487-19616/? W/rota: resume onFailure:
2021-01-11 16:00:49.007 19487-19616/? W/rota: clientException == null:false
2021-01-11 16:00:49.007 19487-19616/? W/rota: serviceException == null:true
没有打印后续rota标签log

**Comment by RealMoMo** [comment]
com.aliyun.dpa:oss-android-sdk:2.9.5

**Comment by wushuai1415** [comment]
clientException有异常信息啊，当服务器返回错误状态码时serviceException才会有值
