### ISSUE TITLE
OKHTTP print it's leaked when download two files in order

### ISSUE THREAD

**Issue by onlycyndi** [aliyun/aliyun-oss-android-sdk#306]
Hi~, I got a problem when download the second file .
log: 
    A connection to https://xxx.xx.xx.xxx/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE)

**Comment by onlycyndi** [comment]
> Hi~, I got a problem when download the second file .
> log:
> A connection to https://118.31.219.198/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE)

And then , I fork this project and upgrade the okhttp version to lasted version , but it doesn't work. also print log:
W/OkHttp: A connection to https://vrsoss.oss-cn-hangzhou.aliyuncs.com/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);

**Comment by wushuai1415** [comment]
Did you close the inputStream after using it

**Comment by onlycyndi** [comment]
> Did you close the inputStream after using it
it's work , thanks .
