### ISSUE TITLE
OSSCompletedCallback多次回调的问题

### ISSUE THREAD

**Issue by pengbs** [aliyun/aliyun-oss-android-sdk#33]
当设置了失败重试次数以后，OSSCompletedCallback的onFailure会回调多次，这样就没法判断是最终失败了还是重试里面的某一次失败了，请问有什么好的办法吗？

**Comment by xuyecan** [comment]
按理不会的，麻烦测试一下。设置了重试的话，只有最后一次重试失败，才会调用回调。
