### ISSUE TITLE
断点下载需要完善

### ISSUE THREAD

**Issue by zhubinsheng** [aliyun/aliyun-oss-android-sdk#335]
[!this.fileStat.md5.equals(fileStat.md5)](https://github.com/aliyun/aliyun-oss-android-sdk/blob/eff5e78d60a1a35cfb4bf3221bffd44978cc5298/oss-android-sdk/src/main/java/com/alibaba/sdk/android/oss/internal/ResumableDownloadTask.java#:~:text=public%20synchronized%20boolean-,isValid,-(InternalRequestOperation%20operation)%20throws)
这个判断需要完善

**Comment by wushuai1415** [comment]
2.9.11已修改

**Comment by zhubinsheng** [comment]
> 2.9.11已修改

现在是2.9.9,请问什么时候发布？是否有开发分支可以先看下

**Comment by wushuai1415** [comment]
> > 2.9.11已修改
> 
> 现在是2.9.9,请问什么时候发布？是否有开发分支可以先看下
2.9.11已经发了两周了

**Comment by zhubinsheng** [comment]
> > > 2.9.11已修改
> > 
> > 
> > 现在是2.9.9,请问什么时候发布？是否有开发分支可以先看下
> > 2.9.11已经发了两周了

https://github.com/aliyun/aliyun-oss-android-sdk/releases
我在tag中没找到，麻烦可以发一下2.9.11的发布链接吗

**Comment by wushuai1415** [comment]
@zhubinsheng 现在master上就是最新的代码

**Comment by zhubinsheng** [comment]
最新的代码测试通过
