### ISSUE TITLE
断点续传添加md5就报错400 InvalidDigest

### ISSUE THREAD

**Issue by FaKenKoala** [aliyun/aliyun-oss-android-sdk#338]
断点续传使用ResumableUploadRequest, 在ObjectMetadata中设置文件内容的Content-MD5, 观察到在最终CompleteMultipartUploadRequest中会设置这个Content-MD5上传，但是就会导致最终上传结果报错 400 InvalidDigest.

请问是使用断点续传禁止设置完整文件的MD5吗？那么怎么保证oss服务器最终合成的文件与本地上传的文件相同呢？有什么方式可以获取到服务器上最终文件的md5值吗？

**Comment by wushuai1415** [comment]
断点不能使用md5，可以用crc https://help.aliyun.com/document_detail/94010.html
