### ISSUE TITLE
断点续传情况下无法设置线程数

### ISSUE THREAD

**Issue by FaKenKoala** [aliyun/aliyun-oss-android-sdk#343]
OSS初始化时可以使用ClientConfiguration的setMaxConcurrentRequest来控制并发数。
在单一上传文件情况下可用。

但是如果使用的是断点续传，一个文件上传拆分成了多个部分上传。此时添加多个文件上传，并不受并发数控制。
这部分有好的建议吗？

**Comment by wushuai1415** [comment]
这个只能由您自己写代码控制了

**Comment by FaKenKoala** [comment]
> 这个只能由您自己写代码控制了

好的，谢谢

**Comment by FaKenKoala** [comment]
> 这个只能由您自己写代码控制了

好的，谢谢
