### ISSUE TITLE
下载进度回调totalSize = -1

### ISSUE THREAD

**Issue by ChenXingB** [aliyun/aliyun-oss-android-sdk#345]
当下载文件较大时（165MB）， totalSize = -1，无法正常显示进度条
sdk:2.9.11

**Comment by wushuai1415** [comment]
抓包看下返回的header

**Comment by ChenXingB** [comment]
"Transfer-Encoding" -> "chunked"
"x-oss-request-id" -> "62947359B25822353113B253"
"x-oss-server-time" -> "192"
"Server" -> "AliyunOSS"
"Connection" -> "keep-alive"
"x-oss-object-type" -> "Multipart"
"Last-Modified" -> "Tue, 24 May 2022 03:16:48 GMT"
"Date" -> "Mon, 30 May 2022 07:33:45 GMT"
"x-oss-storage-class" -> "Standard"
"x-oss-hash-crc64ecma" -> "15228249927083073430"
"Vary" -> "Origin"
"Expires" -> "60000"
"Content-Type" -> "text/plain"

**Comment by ChenXingB** [comment]
"Transfer-Encoding" -> "chunked"
"x-oss-request-id" -> "62947359B25822353113B253"
"x-oss-server-time" -> "192"
"Server" -> "AliyunOSS"
"Connection" -> "keep-alive"
"x-oss-object-type" -> "Multipart"
"Last-Modified" -> "Tue, 24 May 2022 03:16:48 GMT"
"Date" -> "Mon, 30 May 2022 07:33:45 GMT"
"x-oss-storage-class" -> "Standard"
"x-oss-hash-crc64ecma" -> "15228249927083073430"
"Vary" -> "Origin"
"Expires" -> "60000"
"Content-Type" -> "text/plain"

**Comment by wushuai1415** [comment]
应该是gzip压缩了，加个header试试
GetObjectRequest get = new GetObjectRequest(mBucket, object);
Map<String, String> header = new HashMap<String, String>();
header.put("Accept-Encoding", "identity");
get.setRequestHeaders(header);

**Comment by ChenXingB** [comment]
加上以后就可以了，谢谢
