### ISSUE TITLE
DownloadFileRequest 断点续传下载

### ISSUE THREAD

**Issue by guolb** [aliyun/aliyun-oss-android-sdk#37]
DownloadFileRequest 与文档不服；如何断点续传下载？

**Comment by xuyecan** [comment]
请问你使用的是哪个版本呢？2.x以后的版本没有封装断点续传接口，如果需要这个功能，需要根据`指定范围下载`来实现。参考文档：https://help.aliyun.com/document_detail/32048.html?spm=5176.product31815.6.687.MXmTh8

**Comment by zb503758762** [comment]
断点下载没有指定key ?

**Comment by 1019272778** [comment]
@zb503758762 
下载操作前都要创建request，request中都要设置下载object 
详细见：https://help.aliyun.com/document_detail/32048.html?spm=5176.product31815.6.687.MXmTh8

**Comment by XunMengWinter** [comment]
有没有断点下载好用的demo？

**Comment by zhubinsheng** [comment]
> 有没有断点下载好用的demo？

有吗
