### ISSUE TITLE
SignatureDoesNotMatch 求教是神原因啊

### ISSUE THREAD

**Issue by silentcmz** [aliyun/aliyun-oss-android-sdk#38]
<?xml version="1.0" encoding="UTF-8"?>
                                                                   <Error>
                                                                     <Code>SignatureDoesNotMatch</Code>
                                                                     <Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message>
                                                                     <RequestId>582192E82444BF734B40C2A2</RequestId>
                                                                     <HostId>xxx</HostId>
                                                                     <OSSAccessKeyId>zk8nfO0CwDzG3saq</OSSAccessKeyId>
                                                                     <SignatureProvided>dEPZSd7GlWsRY9XS+zyYShTbeiU=</SignatureProvided>
                                                                     <StringToSign>PUT
                                                                   
                                                                   image/jpg
                                                                   Tue, 08 Nov 2016 08:55:03 GMT
OSSCredentialProvider credentialProvider = new OSSPlainTextAKSKCredentialProvider("xxx", "xxxxx");
                                keyid 和key 都是从服务器获取的，但是每次都是SignatureDoesNotMatch，写成阿里云给我的那一套 keyid 和keysercert也不行

**Comment by baiyubin** [comment]
请检查你的keysercert是否正确，如果临时账号请检查是否过期。
