### ISSUE TITLE
程序包com.alibaba.sdk.android.oss.xxx不存在 import com.alibaba.sdk.android.oss.xxx;

### ISSUE THREAD

**Issue by Lunziyuan** [aliyun/aliyun-oss-android-sdk#387]
android gradlew build 大量相似报错。
之前一直正常使用，今天突发archive失败

依赖方式
compile 'com.aliyun.dpa:oss-android-sdk:+'

**Comment by GuoMeng6** [comment]
+1

**Comment by wushuai1415** [comment]
compile 'com.aliyun.dpa:oss-android-sdk:2.9.15',不要自动升级

**Comment by Lunziyuan** [comment]
> compile 'com.aliyun.dpa:oss-android-sdk:2.9.15',不要自动升级

问题已解决 👍
