### ISSUE TITLE
retrofit2.0 okhttp冲突

### ISSUE THREAD

**Issue by xmuSistone** [aliyun/aliyun-oss-android-sdk#39]
你好，使用retrofit2.0，okhttp报错：
![image](https://cloud.githubusercontent.com/assets/12167762/20206319/6cda3092-a81a-11e6-8004-69c485c55b56.png)

我都把okhttp和okio的依赖都删了，还是报这个错，这个怎么弄额？

**Comment by xmuSistone** [comment]
哦。是我弄错了。libs下面自动加入dependency了。删了jar包就不报错了

**Comment by baiyubin** [comment]
好的。谢谢您的反馈。

**Comment by xmuSistone** [comment]
你好，我把文件上传到oss服务器，只是一张图片；想问下，怎么知道这个图片的url呢？

**Comment by xuyecan** [comment]
你好，可以参考文档，从控制台操作: https://help.aliyun.com/document_detail/31887.html?spm=5176.doc31857.6.550.kzX96Y；
也可以自己拼接生成：https://help.aliyun.com/document_detail/31857.html?spm=5176.doc31953.6.581.c1xbBq
