### ISSUE TITLE
OSSCustomSignerCredentialProvider的接口方法signContent返回content字符串中，其中md5一项中如果含有空格的话，而oss签名的时候将空格处理成+，这点不知是个bug还是个坑

### ISSUE THREAD

**Issue by gitwizChen** [aliyun/aliyun-oss-android-sdk#42]
我们用的php的后台，在自签名的时候，content字符串中其中md5校验值并不会将空格处理成+，而我试了把md5中的空格处理成+号后，签名就是对的，所以oss应该也是把md5中的空格处理成+号，还是说oss-android-sdk在返回的md5有问题？

**Comment by 1019272778** [comment]
@gitwizChen 
oss 签名范例如下：
https://help.aliyun.com/document_detail/31951.html
md5后的内容会用base64包裹一下
