### ISSUE TITLE
Glide 加载图片失败.

### ISSUE THREAD

**Issue by songsh** [aliyun/aliyun-oss-android-sdk#48]
Glide.with(context).load(ImageUtils.getUrl(user.getImgUrl())).dontAnimate().error(R.drawable.pic_head_gray).into(civHead)
加载显示不出来，

**Comment by 1019272778** [comment]
无法显示的图片url是从哪里得到的呢？
oss sdk 提供的是把文件上传到oss 进行存储的功能。并不涉及图片展示。

**Comment by 1019272778** [comment]
@songsh 
无法显示的图片url是从哪里得到的呢？
oss sdk 提供的是把文件上传到oss 进行存储的功能。并不涉及图片展示。
