### ISSUE TITLE
上传可不可以不使用SDK进行上传动作

### ISSUE THREAD

**Issue by skyhl** [aliyun/aliyun-oss-android-sdk#59]
现在我们公司为了考虑安全问题，客户端不能得到acessKey 和 临时签名 
现在下载的方法 通过重定向进行下载，客户端不知晓 acessKey 和相关信息
但是上传遇到问题，上传是不是也可以重定向

**Comment by 1019272778** [comment]
不是很理解问题。客户端的STS方式就为了安全的在移动端使用oss sdk而设计的。
暂时还没有上传重定向的计划安排。
