### ISSUE TITLE
[2.x] 如何指定下载CDN？

### ISSUE THREAD

**Issue by edwardaa** [aliyun/aliyun-oss-android-sdk#6]
1.4版本里可以通过`OSSBucket#setCdnAccelerateHostId()`设置CDN。

**Comment by xuyecan** [comment]
这个版本，直接把CDN的加速域名作为一个cname设置进去就好，就是直接作为endpoint进行设置。不过由于当前不支持通过CDN上传，所以，这样设置构造得到的OSSClient，只能用来下载。

如果还需要上传，可以另外构造一个OSSClient。当前版本支持多个OSSClient设置。

**Comment by edwardaa** [comment]
好的，谢谢！
