### ISSUE TITLE
Explicit termination method 'close' not called

### ISSUE THREAD

**Issue by imliujun** [aliyun/aliyun-oss-android-sdk#61]
初始化SDK时，检测到有资源泄露问题
![image](https://user-images.githubusercontent.com/9779970/31324075-4459c93e-ac74-11e7-9003-d91102d00bf4.png)

具体代码：
```java
public static long getLogFileSize(File file) {
        long size = 0;
        if (file != null && file.exists()) {
            try {
                FileInputStream fis = new FileInputStream(file);
                size = (long)fis.available();
            } catch (Exception e) {
                log(Log.ERROR, e.toString());
            }
        }
        return size;
    }
```

获取文件长度使用 `FileInputStream.available()` 后没有关闭 `FileInputStream`

而对于读取文件大小使用 `FileInputStream.available()` 方法的一些弊端网上也是一堆的博客介绍。
我觉得此处使用 `File.length()` 完全可以满足需求。如果必须用流式方法建议加上关闭流的操作。

另外针对本地日志系统，我觉得可以参考其他第三方SDK一样，需要在初始化之前调用是否开启日志打印方法，如果不开启日志打印就不用初始化日志文件了。

**Comment by 1019272778** [comment]
很好的建议。关于FileInputStream 资源泄漏问题，我们也差了资料。在源码中说
Ensures that the close method of this file input stream is called when there are no more references to it.

参见：http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/6-b14/java/io/FileInputStream.java。
不过后来经过内部讨论，我们还是觉得自己控制更好。谢谢。
@imliujun
