### ISSUE TITLE
超时错误：

### ISSUE THREAD

**Issue by Humilton** [aliyun/aliyun-oss-android-sdk#66]
11-03 18:11:05.906 16598-16710/com.vigourbox.vbox:PublishUploadService I/System.out: [CDS]EAGAIN in Recvfrom
11-03 18:11:05.907 16598-16710/com.vigourbox.vbox:PublishUploadService I/System.out: [CDS]read byte is 0
11-03 18:11:05.908 16598-16718/com.vigourbox.vbox:PublishUploadService I/System.out: [CDS]close[38512]
11-03 18:11:05.912 16598-16710/com.vigourbox.vbox:PublishUploadService W/System.err: java.net.SocketTimeoutException: timeout
11-03 18:11:05.918 16598-16710/com.vigourbox.vbox:PublishUploadService W/System.err:     at okio.Okio$4.newTimeoutException(Okio.java:227)
11-03 18:11:05.918 16598-16710/com.vigourbox.vbox:PublishUploadService W/System.err:     at okio.AsyncTimeout.exit(AsyncTimeout.java:284)
11-03 18:11:05.918 16598-16710/com.vigourbox.vbox:PublishUploadService W/System.err:     at okio.AsyncTimeout$2.read(AsyncTimeout.java:240)
11-03 18:11:05.918 16598-16710/com.vigourbox.vbox:PublishUploadService W/System.err:     at okio.RealBufferedSource.indexOf(RealBufferedSource.java:325)
11-03 18:11:05.919 16598-16710/com.vigourbox.vbox:PublishUploadService W/System.err:     at okio.RealBufferedSource.indexOf(RealBufferedSource.java:314)
11-03 18:11:05.919 16598-16710/com.vigourbox.vbox:PublishUploadService W/System.err:     at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:210)
11-03 18:11:05.919 16598-16710/com.vigourbox.vbox:PublishUploadService W/System.err:     at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
11-03 18:11:05.919 16598-16710/com.vigourbox.vbox:PublishUploadService W/System.err:     at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:67)
11-03 18:11:05.919 16598-16710/com.vigourbox.vbox:PublishUploadService W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
11-03 18:11:05.919 16598-16710/com.vigourbox.vbox:PublishUploadService W/System.err:     at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
11-03 18:11:05.919 16598-16710/com.vigourbox.vbox:PublishUploadService W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
11-03 18:11:05.919 16598-16710/com.vigourbox.vbox:PublishUploadService W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
11-03 18:11:05.919 16598-16710/com.vigourbox.vbox:PublishUploadService W/System.err:     at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
11-03 18:11:05.919 16598-16710/com.vigourbox.vbox:PublishUploadService W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
11-03 18:11:05.919 16598-16710/com.vigourbox.vbox:PublishUploadService W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
11-03 18:11:05.919 16598-16710/com.vigourbox.vbox:PublishUploadService W/System.err:     at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
11-03 18:11:05.919 16598-16710/com.vigourbox.vbox:PublishUploadService W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
11-03 18:11:05.919 16598-16710/com.vigourbox.vbox:PublishUploadService W/System.err:     at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
11-03 18:11:05.919 16598-16710/com.vigourbox.vbox:PublishUploadService W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
11-03 18:11:05.919 16598-16710/com.vigourbox.vbox:PublishUploadService W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
11-03 18:11:05.919 16598-16710/com.vigourbox.vbox:PublishUploadService W/System.err:     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:179)
11-03 18:11:05.919 16598-16710/com.vigourbox.vbox:PublishUploadService W/System.err:     at okhttp3.RealCall.execute(RealCall.java:63)
11-03 18:11:05.919 16598-16710/com.vigourbox.vbox:PublishUploadService W/System.err:     at com.alibaba.sdk.android.oss.network.OSSRequestTask.call(OSSRequestTask.java:213)
11-03 18:11:05.919 16598-16710/com.vigourbox.vbox:PublishUploadService W/System.err:     at com.alibaba.sdk.android.oss.network.OSSRequestTask.call(OSSRequestTask.java:39)
11-03 18:11:05.919 16598-16710/com.vigourbox.vbox:PublishUploadService W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
11-03 18:11:05.919 16598-16710/com.vigourbox.vbox:PublishUploadService W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
11-03 18:11:05.920 16598-16710/com.vigourbox.vbox:PublishUploadService W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
11-03 18:11:05.920 16598-16710/com.vigourbox.vbox:PublishUploadService W/System.err:     at java.lang.Thread.run(Thread.java:818)
11-03 18:11:05.920 16598-16710/com.vigourbox.vbox:PublishUploadService W/System.err: Caused by: java.net.SocketTimeoutException
11-03 18:11:05.920 16598-16710/com.vigourbox.vbox:PublishUploadService W/System.err:     at java.net.PlainSocketImpl.read(PlainSocketImpl.java:497)
11-03 18:11:05.920 16598-16710/com.vigourbox.vbox:PublishUploadService W/System.err:     at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:42)
11-03 18:11:05.920 16598-16710/com.vigourbox.vbox:PublishUploadService W/System.err:     at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:242)
11-03 18:11:05.920 16598-16710/com.vigourbox.vbox:PublishUploadService W/System.err:     at okio.Okio$2.read(Okio.java:138)
11-03 18:11:05.920 16598-16710/com.vigourbox.vbox:PublishUploadService W/System.err:     at okio.AsyncTimeout$2.read(AsyncTimeout.java:236)
11-03 18:11:05.920 16598-16710/com.vigourbox.vbox:PublishUploadService W/System.err: 	... 25 more
11-03 18:11:05.932 16598-16710/com.vigourbox.vbox:PublishUploadService I/System.out: [CDS]rx timeout:15000

**Comment by Humilton** [comment]
改配置setSocketTimeout没有作用

**Comment by binghaiwang** [comment]
setSocketTimeout 只有第一次初始化 ossclient 的时候设置 才起作用
