### ISSUE TITLE
org.xml.sax.SAXParseException: Unexpected end of document

### ISSUE THREAD

**Issue by openproject** [aliyun/aliyun-oss-android-sdk#68]
不知道为什么时不时会报这个错，而图片就没传成功：
11-16 16:12:42.227 W/System.err(20928): org.xml.sax.SAXParseException: Unexpected end of document
11-16 16:12:42.228 W/System.err(20928):         at org.apache.harmony.xml.parsers.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:125)
11-16 16:12:42.228 W/System.err(20928):         at com.alibaba.sdk.android.oss.internal.ResponseParsers.parseResponseErrorXML(ResponseParsers.java:580)
11-16 16:12:42.228 W/System.err(20928):         at com.alibaba.sdk.android.oss.network.OSSRequestTask.call(OSSRequestTask.java:182)
11-16 16:12:42.228 W/System.err(20928):         at com.alibaba.sdk.android.oss.network.OSSRequestTask.call(OSSRequestTask.java:36)
11-16 16:12:42.228 W/System.err(20928):         at java.util.concurrent.FutureTask.run(FutureTask.java:237)
11-16 16:12:42.228 W/System.err(20928):         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
11-16 16:12:42.228 W/System.err(20928):         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
11-16 16:12:42.228 W/System.err(20928):         at java.lang.Thread.run(Thread.java:761)

code:
``

            val task = oss.asyncPutObject(put, object : OSSCompletedCallback<PutObjectRequest, PutObjectResult> {
                override fun onFailure(request: PutObjectRequest, clientException: ClientException, serviceException: ServiceException) {

                    Log.d("xxx", "onFailure: " + serviceException)
                }

                override fun onSuccess(request: PutObjectRequest, result: PutObjectResult) {

                    Log.d("xxx", "onSuccess:" + result)
                }
            })
``

**Comment by binghaiwang** [comment]
能提供下图片文件格式么

**Comment by binghaiwang** [comment]
可否发一下服务端返回的xml数据信息，这个是在解析xml的时候出错了

**Comment by binghaiwang** [comment]
serviceException  这个里边的信息麻烦都打印出来 提供一下

**Comment by openproject** [comment]
11-17 11:55:55.263 D/feng    (31280): ---------progress: 99
11-17 11:55:55.263 D/feng    (31280): ---------progress: 99
11-17 11:55:55.263 D/feng    (31280): ---------progress: 99
11-17 11:55:55.263 D/feng    (31280): ---------progress: 99
11-17 11:55:55.263 D/feng    (31280): ---------progress: 100
11-17 11:55:55.299 D/OSS-Android-SDK(31280): [Debug]: response:---------------------
11-17 11:55:55.299 D/OSS-Android-SDK(31280): response code: 400 for url: http://snapshot.yeleplus.com/cid_1000/254f6307-21a8-4244-b002-afaad2a02c51.jpg
11-17 11:55:55.299 D/OSS-Android-SDK(31280): response msg: Bad Request
11-17 11:55:55.299 D/OSS-Android-SDK(31280): responseHeader [connection]: keep-alive
11-17 11:55:55.299 D/OSS-Android-SDK(31280): responseHeader [content-length]: 0
11-17 11:55:55.299 D/OSS-Android-SDK(31280): responseHeader [content-type]: text/html
11-17 11:55:55.299 D/OSS-Android-SDK(31280): responseHeader [eagleid]: 7ae3a4aa15108909535386286e
11-17 11:55:55.299 D/OSS-Android-SDK(31280): responseHeader [server]: Tengine
11-17 11:55:55.299 D/OSS-Android-SDK(31280): responseHeader [timing-allow-origin]: *
11-17 11:55:55.299 D/OSS-Android-SDK(31280): responseHeader [via]: kunlun7.cn198[0,400-1,M], kunlun10.cn198[1,0]
11-17 11:55:55.299 D/OSS-Android-SDK(31280): responseHeader [x-swift-error]: request parse msg error
11-17 11:55:55.392 W/System.err(31280): org.xml.sax.SAXParseException: Unexpected end of document
11-17 11:55:55.399 W/System.err(31280):         at org.apache.harmony.xml.parsers.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:125)
11-17 11:55:55.399 W/System.err(31280):         at com.alibaba.sdk.android.oss.internal.ResponseParsers.parseResponseErrorXML(ResponseParsers.java:580)
11-17 11:55:55.399 W/System.err(31280):         at com.alibaba.sdk.android.oss.network.OSSRequestTask.call(OSSRequestTask.java:182)
11-17 11:55:55.400 W/System.err(31280):         at com.alibaba.sdk.android.oss.network.OSSRequestTask.call(OSSRequestTask.java:36)
11-17 11:55:55.400 W/System.err(31280):         at java.util.concurrent.FutureTask.run(FutureTask.java:237)
11-17 11:55:55.400 W/System.err(31280):         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
11-17 11:55:55.400 W/System.err(31280):         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
11-17 11:55:55.400 W/System.err(31280):         at java.lang.Thread.run(Thread.java:761)
11-17 11:55:55.401 D/OSS-Android-SDK(31280): [Debug]: [run] - retry, retry type: OSSRetryTypeShouldNotRetry

**Comment by openproject** [comment]
这个异常会导致，进入不了 onFailure，没有抛出的 exception, 这是比较尴尬的

**Comment by 1019272778** [comment]
@openproject 能帮忙提供一下不能正常解析的xml信息吗？我们看看是什么原因
