### ISSUE TITLE
[2.x] 怎么设置Bucket/Object的ACL

### ISSUE THREAD

**Issue by edwardaa** [aliyun/aliyun-oss-android-sdk#7]
1.4版本可以通过`Bucket.setBucketACL("public-read")`来设置`ACL`，2.x里没有找到对应方法。
如果不设置ACL，PutObject的默认ACL是什么？

**Comment by xuyecan** [comment]
1.4版本，设置这个ACL是用来决定某个接口是否需要鉴权，这个ACL需要和控制台的设置保持一致。

新版本不需要做这个指明，而是由用户自己决定操作是否鉴权。默认是都需要鉴权的。如果bucket是公共的，需要不经过鉴权就操作某个接口，那么，只要构造request的时候，调用一下，request.setIsAuthorizationRequired(false)就可以了。

**Comment by edwardaa** [comment]
之前**误**以为`ACL`是用来指明Object的`x-oss-object-acl`属性，现在明白了，谢谢！
