### ISSUE TITLE
一个建议，放个精简的不带gradle的下载吧

### ISSUE THREAD

**Issue by ccimage** [aliyun/aliyun-oss-android-sdk#73]
SDK 80多M有点大啊，发现里面放了gradle3.3 汗。
主要是github的下载也不是完全流畅的（原因你懂的），用浏览器下不了因为失败就重新开始了。
用迅雷也失败了5次，还好有续传。
我相信我的网络不会是最糟糕的

**Comment by 1019272778** [comment]
@ccimage oss sdk的代码已经开源。你可以下载oss-android-sdk 中的代码。

**Comment by 1019272778** [comment]
你是下载整个sdk，然后compile project 的方式吗？我测试过，oss SDK lib jar 包只有200k
