### ISSUE TITLE
上传超时问题

### ISSUE THREAD

**Issue by androidWht** [aliyun/aliyun-oss-android-sdk#75]
android sdk调用asyncResumableUpload上传文件，在上传过程中断开网络，没有失败的回调,并且在恢复网络后，请求也没有任何反应（没有成功，也没有失败），这个问题很不解

**Comment by jerryisbusy** [comment]
同样的问题，我这边也出现了，两台华为设备，其他设备上没有出现。
这个问题已经存在这么久了，客服还让我提交issue。唉...

**Comment by 1019272778** [comment]
@androidWht 你好，请问有具体的异常信息吗？另，也可以打开enablelog功能。看看log文件中的提示

**Comment by jerryisbusy** [comment]
@1019272778 开启过，没有错误日志打印。同样的方式，如果使用的是PutObjectRequest，可以打印出错误堆栈信息的。

**Comment by 1019272778** [comment]
@jerryisbusy 请问你用的版本是？

**Comment by androidWht** [comment]
@1019272778 我这边也是这样，很容易出现，没有错误日志，而且出现整个功能都死掉了，api调用没有任何效果，也不再有日志输出。我使用的是单例的OSS对象。里面应该是死锁了。使用DDMS查看发现大量oss-android-extensionapi-thread，oss-android-api-thread,oss-android-mulipart-thread线程都处于Wait状态

**Comment by androidWht** [comment]
@1019272778 版本2.4.5，应该是最新的。

**Comment by jerryisbusy** [comment]
@1019272778 最新版本

**Comment by 1019272778** [comment]
@androidWht @jerryisbusy 目前我们反复测试没有出现这样的情况。具体是在什么手机上出现的呢？另是否可以用complie project 的方式看看问题出现在哪里？辛苦了。现在确实无法复线场景

**Comment by androidWht** [comment]
就是死锁了。用小文件测试下（我这边测试出现是几M的小文件，asyncResumableUpload上传）。
HUAWEI P9，EVA-AL00，7.0版本。其它手机也有出现。
![_20180123100105](https://user-images.githubusercontent.com/10459917/35254457-4028c48c-0025-11e8-9d16-4f52a85bfa6e.png)
![_20180123100127](https://user-images.githubusercontent.com/10459917/35254463-462a9662-0025-11e8-99c2-2aae97cdfd1b.png)
![_20180123100228](https://user-images.githubusercontent.com/10459917/35254466-4b46a0e6-0025-11e8-925b-6a50462eb77e.png)

**Comment by androidWht** [comment]
应该是死锁，5个oss-android-extensionapi-thread wait在doMultipartUpload方法，25个oss-android-multipart-thread线程在等待任务。
![_20180123111713](https://user-images.githubusercontent.com/10459917/35256472-0a23470e-002f-11e8-9367-d233851b87e2.png)
![_20180123111728](https://user-images.githubusercontent.com/10459917/35256479-0fc8b11c-002f-11e8-8bd4-47b496640373.png)

**Comment by 1019272778** [comment]
@androidWht @jerryisbusy 
bug已经fix。可以查看bugfix-resumeuploadfreeze分支。

**Comment by jerryisbusy** [comment]
@1019272778 出新版本了？

**Comment by jerryisbusy** [comment]
@1019272778 我之前又测试了几台机器，发现跟设备也没有关系。
之前没出错的meizu pro 6s 也出现了同样的问题。

**Comment by jerryisbusy** [comment]
@1019272778 试过了，还是不行。

**Comment by 1019272778** [comment]
@jerryisbusy 还没有出新版本。是在bugfix-resumeuploadfreeze分支中

**Comment by jerryisbusy** [comment]
具体什么时候发新版本？？
我们等着用！！

**Comment by 1019272778** [comment]
@jerryisbusy 如果你要是着急。可以下载bugfix-resumeuploadfreeze分支。然后用compile project的方式来验证

**Comment by jerryisbusy** [comment]
@1019272778
 我用了bugfix-resumeuploadfreeze 分支的代码测试了，发现没有解决问题。
1. 上传过程中，断网，错误的确有回调了，但仅限一次。联网后，重试，上传到一半时，再次断网，问题又出来了，依然死锁
2. 上传过程中，断网，错误返回后，再联网， 重新上传， 断网前的上传进度全部丢失了，又要从0开始上传了，这不符合‘断点续传’的特性。

**Comment by 1019272778** [comment]
@jerryisbusy 非常感谢。
再次断网，依然死锁的问题已经修正。
不过没发现进度是从0上传的，还是延续了上次的断点记录。
你是否在代码中调用过cancel()方法？如果调用过。需要设置
request.setDeleteUploadOnCancelling(false);
否则本地的断点文件记录无法保存

**Comment by burgessjp** [comment]
> @jerryisbusy 非常感谢。
> 再次断网，依然死锁的问题已经修正。
> 不过没发现进度是从0上传的，还是延续了上次的断点记录。
> 你是否在代码中调用过cancel()方法？如果调用过。需要设置
> request.setDeleteUploadOnCancelling(false);
> 否则本地的断点文件记录无法保存

这个问题现在确定是解决了吗？我现在用的 2.9.1 版本这个问题还是必现，与机型无关。

**Comment by SeanSMh** [comment]
> > @jerryisbusy 非常感谢。
> > 再次断网，依然死锁的问题已经修正。
> > 不过没发现进度是从0上传的，还是延续了上次的断点记录。
> > 你是否在代码中调用过cancel()方法？如果调用过。需要设置
> > request.setDeleteUploadOnCancelling(false);
> > 否则本地的断点文件记录无法保存
> 
> 这个问题现在确定是解决了吗？我现在用的 2.9.2 版本这个问题还是必现，与机型无关。
2.9.3版本依然出现了

**Comment by SeanSMh** [comment]
版本2.9.3，Android 10，荣耀magic2，依然出现该问题
