### ISSUE TITLE
上传失败问题

### ISSUE THREAD

**Issue by androidWht** [aliyun/aliyun-oss-android-sdk#78]
使用asyncResumableUpload上传设置setDeleteUploadOnCancelling为false，在上传过程中断开网络（部分上传，上传请求会死掉，无任何响应），此时调用task的cancel，再次发起上传请求，
出现ClientException("The uploading file is inconsistent with before"),

**Comment by 1019272778** [comment]
@androidWht 参见#75

**Comment by 1019272778** [comment]
@androidWht 可以试一下新版本
