### ISSUE TITLE
endpoint 问题

### ISSUE THREAD

**Issue by zzy1147** [aliyun/aliyun-oss-android-sdk#79]
endpoint设置为http://on.image.com/image格式时。
请求地址为什么要设置http://on.image.com/+“objectkey”格式

>`String originHost = endpoint.getHost();

        // If it'd not a CName or it's in the CName exclude list, the host should be prefixed with the bucket name.
        if (!OSSUtils.isCname(originHost) && bucketName != null) {
            originHost = bucketName + "." + originHost;
        }

        String urlHost = null;
        if (isHttpDnsEnable()) {
            urlHost = HttpdnsMini.getInstance().getIpByHostAsync(originHost);
        } else {
            OSSLog.logDebug("[buildCannonicalURL], disable httpdns");
        }

        // The urlHost is null when the asynchronous DNS resolution API never returns IP.
        if (urlHost == null) {
            urlHost = originHost;
        }

        String headerHost = originHost;
        if (OSSUtils.isCname(originHost) && this.isInCustomCnameExcludeList() && bucketName != null) {
            headerHost = bucketName + "." + originHost;
        }

        addHeader(OSSHeaders.HOST, headerHost);

        baseURL = scheme + "://" + urlHost;
        if (objectKey != null) {
            baseURL += "/" + HttpUtil.urlEncode(objectKey, OSSConstants.DEFAULT_CHARSET_NAME);
        }`

**Comment by 1019272778** [comment]
如果需要设置自定义域名的访问。on.image.com 对应某一个bucket。所以访问object 的格式为设置http://on.image.com/+“objectkey”格式
更多详情请看：https://help.aliyun.com/document_detail/31836.html 介绍
