### ISSUE TITLE
x-oss-security-token

### ISSUE THREAD

**Issue by dadakkk** [aliyun/aliyun-oss-android-sdk#85]
OSSUtils.class
headersToSign.put(lowerKey, header.getValue().trim());
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.trim()' on a null object reference

**Comment by 1019272778** [comment]
@dadakkk content-type,date等字段是oss 签名需要的字段内容。具体的签名内容详见如下内容
https://help.aliyun.com/document_detail/31951.html
