### ISSUE TITLE
InvalidAccessKeyId  过期后再次提交问题

### ISSUE THREAD

**Issue by GoAheadComeOn** [aliyun/aliyun-oss-android-sdk#86]
你好如果首次提交时InvalidAccessKeyId  不合法（其他参数正常），报错信息如下
    <Error>
                                                             <Code>InvalidAccessKeyId</Code>
                                                             <Message>The OSS Access Key Id you provided does not exist in our records.</Message>
                                                             <RequestId>5A5F1BC32A8F223E5E7353AD</RequestId>
                                                             <HostId>evcard.oss-cn-shanghai.aliyuncs.com</HostId>
                                                             <OSSAccessKeyId>fdg3gr3evfdbgfdnbvxczvZgt4hg4ert</OSSAccessKeyId>
                                                           </Error>

如果这时我重新请求InvalidAccessKeyId等信息后，再次提交文件（参数均是新的）还是一直报上面的错误信息，这个时候需要手动把APP杀掉之后才能正常提交文件，检查代码后本地代码没有缓存任何关于InvalidAccessKeyId等参数。

请问sdk是不是对手机做了类似安全验证的东西

**Comment by 1019272778** [comment]
@GoAheadComeOn 
SDK 并不会保存用户提交的账户信息。 另这个校验逻辑是服务器返回的，并不是在SDK层校验的。能贴一下使用的代码吗？

**Comment by GoAheadComeOn** [comment]
不好意思，发现是我代码问题，在过期后没有在OSSStsTokenCredentialProvider重新设置AccsessKeyId等数据
