### ISSUE TITLE
InvalidAccessKeyId过期后再次上传文件问题

### ISSUE THREAD

**Issue by GoAheadComeOn** [aliyun/aliyun-oss-android-sdk#87]
用过期的InvalidAccessKeyId上传文件，失败后重新请求InvalidAccessKeyId等参数再次提交还是提交失败，失败信息如下
<Error>
                                                              <Code>InvalidAccessKeyId</Code>
                                                              <Message>The OSS Access Key Id you provided does not exist in our records.</Message>
                                                              <RequestId>5A603C11F1C42E8EF6CE2631</RequestId>
                                                              <HostId>evcard.oss-cn-shanghai.aliyuncs.com</HostId>
                                                              <OSSAccessKeyId>fdg3gr3evfdbgfdnbvxczvZgt4hg4ert</OSSAccessKeyId>
                                                            </Error>

**Comment by Colaman0** [comment]
请问这是什么原因呢? 你解决了吗

**Comment by GoAheadComeOn** [comment]
很久之前的事情了，不太记得了，不过这个问题是解决了，应该是我们这边的问题，不是阿里的问题。
看上面的日志应该还是获取的key不存在，那么问题可能就出在两个点，一个是后台返回的key是错误的，这里需要后端同事去查，另一个就是你本地处理的时候不小心操作了key导致，这个需要你自己打下log仔细对比下参数
