### ISSUE TITLE
上传过程中，中断网络，没有错误回调到上层,onFailure方法没有执行

### ISSUE THREAD

**Issue by jerryisbusy** [aliyun/aliyun-oss-android-sdk#89]
上传过程中，中断网络，没有错误回调到上层,onFailure方法没有执行，
在两台华为设备上出现了：
  一台是：huawei Honor 8 Lite，7.0系统，EMUI:5.0.1
一台是: huawei MLA-AL00  6.0系统，EMUI：4.1.3

**Comment by 1019272778** [comment]
@jerryisbusy 参见#75
