### ISSUE TITLE
上传失败

### ISSUE THREAD

**Issue by chordw** [aliyun/aliyun-oss-android-sdk#98]
W/System.err: com.alibaba.sdk.android.oss.ClientException: File descriptor closed
W/System.err: [ErrorMessage]: File descriptor closed
W/System.err:     at com.alibaba.sdk.android.oss.network.OSSRequestTask.call(OSSRequestTask.java:166)
W/System.err:     at com.alibaba.sdk.android.oss.network.OSSRequestTask.call(OSSRequestTask.java:215)
W/System.err:     at com.alibaba.sdk.android.oss.network.OSSRequestTask.call(OSSRequestTask.java:215)
W/System.err:     at com.alibaba.sdk.android.oss.network.OSSRequestTask.call(OSSRequestTask.java:36)
W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/System.err:     at java.lang.Thread.run(Thread.java:818)
W/System.err: Caused by: java.io.IOException: File descriptor closed
W/System.err:     at libcore.io.Posix.readBytes(Native Method)
W/System.err:     at libcore.io.Posix.read(Posix.java:147)
W/System.err:     at libcore.io.BlockGuardOs.read(BlockGuardOs.java:230)
W/System.err:     at libcore.io.IoBridge.read(IoBridge.java:472)
W/System.err:     at java.io.FileInputStream.read(FileInputStream.java:177)
W/System.err:     at okio.Okio$2.read(Okio.java:139)
W/System.err:     at com.alibaba.sdk.android.oss.network.ProgressTouchableRequestBody.writeTo(ProgressTouchableRequestBody.java:59)
W/System.err:     at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:62)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)

**Comment by chordw** [comment]
上传图片时出现这个异常

**Comment by 1019272778** [comment]
@chordw 您可以先看一下app中的范例是如何上传文件。有通过文件路径，二进制数组等方式。您可以参考。这些都有测试例子。另，根据往上的信息，这个错误可能是因为文件流操作引起。您也可以参考。

**Comment by chordw** [comment]
谢谢。这个问题也不是经常发生：比如第一次编译生成apk之后可以上传，修改部分代码后重新编译生成apk就有可能不能上传，我只有把androidstudio  invalid caches 后重新打开再次编译apk就可以成功了，这个具体原因我也不清楚，目前我只能这么做吧
